# -*- coding: utf-8 -*-
"""International Data tab mixin extracted from fm26_generator_gui_2.py backups.

Generated by: fm26_patch_gui_fix_international_mixin_wiring_v4.py
"""

from __future__ import annotations



import json
import tkinter as tk
from tkinter import ttk, messagebox

# If the main GUI defines a tooltip helper, reuse it; otherwise no-op.
try:
    from __main__ import _attach_tooltip  # type: ignore
except Exception:
    def _attach_tooltip(widget, text: str):
        return

class InternationalSubtabMixin:
    def _add_international_caps_list(self, parent, row: int, prefix: str, list_key: str, title: str, apps_label: str, goals_label: str):
        """Reusable list editor for Other Nation Caps / Other Nation Youth Caps."""
        box = ttk.LabelFrame(parent, text=title)
        box.grid(row=row, column=0, sticky="ew", padx=8, pady=(0, 8))
        box.columnconfigure(0, weight=1)

        nation_rows = list(self._load_master_library_rows(kind="nation"))
        nation_labels = [x.get("nation_name") or x.get("name") or "" for x in nation_rows]
        nation_labels = [x for x in nation_labels if x]


        # Mode: Random / Custom / Don't set (default Don't set)
        mode_attr = f"{prefix}_{list_key}_mode"
        mode_var = getattr(self, mode_attr, None)
        if mode_var is None:
            mode_var = tk.StringVar(value="none")
            setattr(self, mode_attr, mode_var)

        modef = ttk.Frame(box)
        modef.grid(row=0, column=0, sticky="w", padx=6, pady=(6, 2))
        ttk.Label(modef, text="Mode:").grid(row=0, column=0, sticky="w")
        ttk.Radiobutton(modef, text="Random", variable=mode_var, value="random").grid(row=0, column=1, sticky="w", padx=(10, 0))
        ttk.Radiobutton(modef, text="Custom", variable=mode_var, value="custom").grid(row=0, column=2, sticky="w", padx=(10, 0))
        ttk.Radiobutton(modef, text="Don\'t set", variable=mode_var, value="none").grid(row=0, column=3, sticky="w", padx=(10, 0))

        items_attr = f"{prefix}_{list_key}_items"
        clip_attr = f"{prefix}_{list_key}_clipboard"
        items = getattr(self, items_attr, None)
        if items is None:
            items = []
            setattr(self, items_attr, items)
        if not hasattr(self, clip_attr):
            setattr(self, clip_attr, None)

        def _v(name: str, default=""):
            attr = f"{prefix}_{list_key}_{name}"
            vv = getattr(self, attr, None)
            if vv is None:
                vv = tk.StringVar(value=str(default))
                setattr(self, attr, vv)
            return vv

        nation_var = _v("nation", "")
        apps_var = _v("apps", "0")
        goals_var = _v("goals", "0")
        comment_var = _v("comment", "")

        btnbar = ttk.Frame(box)
        btnbar.grid(row=1, column=0, sticky="ew", padx=6, pady=(6, 4))
        for c in range(10):
            btnbar.columnconfigure(c, weight=0)
        btnbar.columnconfigure(9, weight=1)

        listwrap = ttk.Frame(box)
        listwrap.grid(row=2, column=0, sticky="nsew", padx=6, pady=(0, 6))
        listwrap.columnconfigure(0, weight=1)
        listwrap.rowconfigure(1, weight=1)

        count_var = tk.StringVar(value=f"{len(items)} items")
        ttk.Label(listwrap, textvariable=count_var).grid(row=0, column=0, sticky="w", pady=(0, 3))

        treefrm = ttk.Frame(listwrap)
        treefrm.grid(row=1, column=0, sticky="nsew")
        treefrm.columnconfigure(0, weight=1)
        treefrm.rowconfigure(0, weight=1)

        tree = ttk.Treeview(treefrm, columns=("nation", "apps", "goals"), show="headings", height=5, selectmode="browse")
        tree.heading("nation", text="Nation")
        tree.heading("apps", text=apps_label)
        tree.heading("goals", text=goals_label)
        tree.column("nation", width=220, anchor="w")
        tree.column("apps", width=150, anchor="center")
        tree.column("goals", width=150, anchor="center")
        tree.grid(row=0, column=0, sticky="nsew")
        yscroll = ttk.Scrollbar(treefrm, orient="vertical", command=tree.yview)
        yscroll.grid(row=0, column=1, sticky="ns")
        tree.configure(yscrollcommand=yscroll.set)
        setattr(self, f"{prefix}_{list_key}_tree", tree)

        editf = ttk.Frame(box)
        editf.grid(row=3, column=0, sticky="ew", padx=6, pady=(0, 6))
        # [INTL_STARTUP_HIDE_V4]
        if (mode_var.get() or "").strip().lower() != "custom":
            try:
                editf.grid_remove()
            except Exception:
                pass
        self._bind_mode_showhide(mode_var, "custom", [editf], clear_vars=[nation_var, apps_var, goals_var, comment_var])
        self._bind_mode_showhide(mode_var, "custom", [editf], clear_vars=[nation_var, apps_var, goals_var, comment_var])
        for c in range(8):
            editf.columnconfigure(c, weight=1 if c in (1, 3, 5) else 0)

        ttk.Label(editf, text="Nation").grid(row=0, column=0, sticky="w", padx=(0, 6), pady=3)
        nation_picker = self._make_searchable_picker(editf, nation_var, nation_labels, width=30)
        nation_picker.grid(row=0, column=1, sticky="ew", padx=(0, 10), pady=3)

        ttk.Label(editf, text=apps_label).grid(row=0, column=2, sticky="w", padx=(0, 6), pady=3)
        apps_entry = ttk.Entry(editf, textvariable=apps_var, width=10)
        apps_entry.grid(row=0, column=3, sticky="w", padx=(0, 10), pady=3)

        ttk.Label(editf, text=goals_label).grid(row=0, column=4, sticky="w", padx=(0, 6), pady=3)
        goals_entry = ttk.Entry(editf, textvariable=goals_var, width=10)
        goals_entry.grid(row=0, column=5, sticky="w", padx=(0, 10), pady=3)

        _syncing = {"on": False}

        def _norm_int_str(v: str) -> str:
            t = (v or "").strip()
            if t == "":
                return "0"
            try:
                return str(int(float(t)))
            except Exception:
                return t

        def _rec_from_editor():
            return {
                "nation": (nation_var.get() or "").strip(),
                "apps": _norm_int_str(apps_var.get()),
                "goals": _norm_int_str(goals_var.get()),
                "comment": (comment_var.get() or "").strip(),
            }

        def _set_editor(rec=None):
            _syncing["on"] = True
            try:
                rec = rec or {}
                nation_var.set(rec.get("nation", "") or "")
                apps_var.set(str(rec.get("apps", "0") or "0"))
                goals_var.set(str(rec.get("goals", "0") or "0"))
                comment_var.set(rec.get("comment", "") or "")
            finally:
                _syncing["on"] = False

        def _sel_idx():
            sel = tree.selection()
            if not sel:
                return None
            try:
                return int(str(sel[0]))
            except Exception:
                return None

        def _refresh(select_idx=None):
            for iid in tree.get_children():
                tree.delete(iid)
            for idx, rec in enumerate(items):
                tree.insert("", "end", iid=str(idx), values=(
                    rec.get("nation", "") or "",
                    rec.get("apps", "0") or "0",
                    rec.get("goals", "0") or "0",
                ))
            count_var.set(f"{len(items)} items")
            if select_idx is not None and 0 <= int(select_idx) < len(items):
                iid = str(int(select_idx))
                try:
                    tree.selection_set(iid)
                    tree.focus(iid)
                    tree.see(iid)
                except Exception:
                    pass

        def _on_select(event=None):
            idx = _sel_idx()
            if idx is None or idx < 0 or idx >= len(items):
                return
            _set_editor(dict(items[idx]))

        def _update_selected_from_editor(*_):
            if _syncing["on"]:
                return
            idx = _sel_idx()
            if idx is None or idx < 0 or idx >= len(items):
                return
            items[idx] = _rec_from_editor()
            _refresh(select_idx=idx)

        def _add():
            items.append(_rec_from_editor())
            _refresh(select_idx=len(items) - 1)

        def _duplicate():
            idx = _sel_idx()
            if idx is None or idx < 0 or idx >= len(items):
                return
            items.insert(idx + 1, dict(items[idx]))
            _refresh(select_idx=idx + 1)

        def _remove():
            idx = _sel_idx()
            if idx is None or idx < 0 or idx >= len(items):
                return
            del items[idx]
            new_idx = min(idx, len(items) - 1)
            _refresh(select_idx=new_idx if new_idx >= 0 else None)
            if not items:
                _set_editor(None)

        def _copy():
            idx = _sel_idx()
            if idx is None or idx < 0 or idx >= len(items):
                return
            setattr(self, clip_attr, dict(items[idx]))

        def _paste():
            clip = getattr(self, clip_attr, None)
            if not isinstance(clip, dict):
                return
            idx = _sel_idx()
            if idx is None:
                items.append(dict(clip))
                idx = len(items) - 1
            else:
                items.insert(idx + 1, dict(clip))
                idx += 1
            _refresh(select_idx=idx)

        def _clear():
            items.clear()
            _refresh()
            _set_editor(None)

        def _add_comment():
            idx = _sel_idx()
            if idx is None or idx < 0 or idx >= len(items):
                try:
                    messagebox.showinfo(title, "Select an item first, then click Add Comment.")
                except Exception:
                    pass
                return
            rec = dict(items[idx])
            existing = (rec.get("comment") or "").strip()
            rec["comment"] = existing if existing else "Comment"
            items[idx] = rec
            _set_editor(rec)
            _refresh(select_idx=idx)

        buttons = [
            ("Add", _add),
            ("Duplicate", _duplicate),
            ("Remove", _remove),
            ("Copy", _copy),
            ("Paste", _paste),
            ("Clear", _clear),
            ("Add Comment", _add_comment),
        ]
        for i, (txt, cmd) in enumerate(buttons):
            ttk.Button(btnbar, text=txt, command=lambda _f=cmd: (mode_var.set("custom"), _f())).grid(row=0, column=i, sticky="w", padx=(0, 4))

        tree.bind("<<TreeviewSelect>>", _on_select, add="+")
        for vv in (nation_var, apps_var, goals_var, comment_var):
            try:
                vv.trace_add("write", _update_selected_from_editor)
            except Exception:
                pass

        _refresh()
        if items:
            _refresh(select_idx=0)
        return box

    def _add_international_data_section(self, parent, row: int, prefix: str):
        """International Data tab UI (separate from Details tab)."""
        wrap = ttk.Frame(parent)
        wrap.grid(row=row, column=0, columnspan=2, sticky="ew", padx=4, pady=4)
        wrap.columnconfigure(0, weight=1)

        infof = ttk.LabelFrame(wrap, text="International Data")
        infof.grid(row=0, column=0, sticky="ew", padx=4, pady=(0, 8))
        infof.columnconfigure(2, weight=1)

        nation_rows = list(self._load_master_library_rows(kind="nation"))
        nation_labels = [x.get("nation_name") or x.get("name") or "" for x in nation_rows]
        nation_labels = [x for x in nation_labels if x]

        def _iv(key: str, default=""):
            mode_attr = f"{prefix}_intl_{key}_mode"
            value_attr = f"{prefix}_intl_{key}_value"
            mv = getattr(self, mode_attr, None)
            if mv is None:
                mv = tk.StringVar(value="none")
                setattr(self, mode_attr, mv)
            vv = getattr(self, value_attr, None)
            if vv is None:
                vv = tk.StringVar(value=str(default))
                setattr(self, value_attr, vv)
            return mv, vv

        rows = [
            ("International Apps", "international_apps", "int", ""),
            ("International Goals", "international_goals", "int", ""),
            ("U21 International Apps", "u21_international_apps", "int", ""),
            ("U21 International Goals", "u21_international_goals", "int", ""),
            ("International Debut Date", "international_debut_date", "date", ""),
            ("International Debut Against", "international_debut_against", "nation", ""),
            ("Date Of First International Goal", "first_international_goal_date", "date", ""),
            ("First International Goal Against", "first_international_goal_against", "nation", ""),
        ]

        rr = 0
        for label, key, kind, default in rows:
            mode_var, value_var = _iv(key, default)
            ttk.Label(infof, text=label).grid(row=rr, column=0, sticky="w", padx=6, pady=3)
            rb_rand = ttk.Radiobutton(infof, text="Random", variable=mode_var, value="random")
            rb_custom = ttk.Radiobutton(infof, text="Custom", variable=mode_var, value="custom")
            rb_none = ttk.Radiobutton(infof, text="Don\'t set", variable=mode_var, value="none")
            rb_rand.grid(row=rr, column=1, sticky="w", padx=(6, 2))
            rb_custom.grid(row=rr, column=1, sticky="w", padx=(85, 2))
            rb_none.grid(row=rr, column=1, sticky="w", padx=(165, 2))

            if kind == "nation":
                w = self._make_searchable_picker(infof, value_var, nation_labels, width=48)
                w.grid(row=rr, column=2, sticky="ew", padx=6, pady=3)                # [INTL_STARTUP_HIDE]
                # [INTL_STARTUP_HIDE_V4]
                if (mode_var.get() or "").strip().lower() != "custom":
                    try:
                        w.grid_remove()
                    except Exception:
                        pass
                if (mode_var.get() or "").strip().lower() != "custom":
                    try:
                        w.grid_remove()
                    except Exception:
                        pass

                self._bind_mode_showhide(mode_var, "custom", [w], clear_vars=[value_var])
            elif kind == "date":
                rowf = ttk.Frame(infof)
                rowf.grid(row=rr, column=2, sticky="ew", padx=6, pady=3)                # [INTL_STARTUP_HIDE]
                # [INTL_STARTUP_HIDE_V4]
                if (mode_var.get() or "").strip().lower() != "custom":
                    try:
                        rowf.grid_remove()
                    except Exception:
                        pass
                if (mode_var.get() or "").strip().lower() != "custom":
                    try:
                        rowf.grid_remove()
                    except Exception:
                        pass

                rowf.columnconfigure(0, weight=1)
                e = ttk.Entry(rowf, textvariable=value_var)
                e.grid(row=0, column=0, sticky="ew")
                b = ttk.Button(rowf, text="📅", width=3, command=lambda v=value_var: self._open_calendar(v))
                b.grid(row=0, column=1, sticky="w", padx=(4, 0))
                self._bind_mode_showhide(mode_var, "custom", [rowf], clear_vars=[value_var])
            else:
                w = ttk.Entry(infof, textvariable=value_var)
                w.grid(row=rr, column=2, sticky="ew", padx=6, pady=3)                # [INTL_STARTUP_HIDE]
                # [INTL_STARTUP_HIDE_V4]
                if (mode_var.get() or "").strip().lower() != "custom":
                    try:
                        w.grid_remove()
                    except Exception:
                        pass
                if (mode_var.get() or "").strip().lower() != "custom":
                    try:
                        w.grid_remove()
                    except Exception:
                        pass

                self._bind_mode_showhide(mode_var, "custom", [w], clear_vars=[value_var])
            rr += 1

        self._add_international_caps_list(wrap, row=1, prefix=prefix, list_key="other_nation_caps", title="Other Nation Caps", apps_label="International Apps", goals_label="International Goals")
        self._add_international_caps_list(wrap, row=2, prefix=prefix, list_key="other_nation_youth_caps", title="Other Nation Youth Caps", apps_label="U21 International Apps", goals_label="U21 International Goals")

    def _build_batch_international_tab(self) -> None:
        frm = self.batch_international_body
        for c in range(2):
            frm.columnconfigure(c, weight=1)
        # [INTL_TOGGLE_VARS_INIT_V3_BATCH]
        if not hasattr(self, "batch_intl_show_files"):
            self.batch_intl_show_files = tk.BooleanVar(value=False)
        if not hasattr(self, "batch_intl_show_gen"):
            self.batch_intl_show_gen = tk.BooleanVar(value=False)


        # Mirrored file inputs on International Data tab (synced with Other/Details)
        paths = ttk.LabelFrame(frm, text="File inputs")
        paths.grid(row=1, column=0, sticky="ew", padx=8, pady=(0, 8))
        paths.columnconfigure(1, weight=1)
        self.batch_international_paths_frame = paths

        def row_file(r, label, var, is_save=False):
            ttk.Label(paths, text=label).grid(row=r, column=0, sticky="w", padx=(8, 6), pady=6)
            ttk.Entry(paths, textvariable=var).grid(row=r, column=1, sticky="ew", padx=(0, 6), pady=6)
            if is_save:
                ttk.Button(paths, text="Browse…", command=lambda: self._pick_save_xml(var)).grid(row=r, column=2, sticky="ew", padx=(0, 8), pady=6)
            else:
                ttk.Button(paths, text="Browse…", command=lambda: self._pick_open_file(var)).grid(row=r, column=2, sticky="ew", padx=(0, 8), pady=6)

        row_file(0, "master_library.csv:", self.batch_clubs, is_save=False)
        row_file(1, "Male first names CSV:", self.batch_first, is_save=False)
        row_file(2, "Female first names CSV:", self.batch_female_first, is_save=False)
        row_file(3, "Common names CSV:", self.batch_common_names, is_save=False)
        row_file(4, "Surnames CSV:", self.batch_surn, is_save=False)
        row_file(5, "Output XML:", self.batch_out, is_save=True)
        row_file(6, "Generator script:", self.batch_script, is_save=False)
        row_file(7, "Region mapping CSV (placeholder):", self.batch_region_map_csv, is_save=False)


        togg = ttk.Frame(frm)
        togg.grid(row=0, column=0, sticky="e", padx=8, pady=(0, 8))

        def _apply_intl_tab_vis():
            try:
                (paths.grid if getattr(self, "batch_intl_show_files").get() else paths.grid_remove)()
            except Exception:
                pass
            try:
                (genf.grid if getattr(self, "batch_intl_show_gen").get() else genf.grid_remove)()
            except Exception:
                pass

        _apply_intl_tab_vis()

        for c in range(6):
            pass  # [AUTO_EMPTY_FOR_FIX]
        # # [PATCH TOOLTIP MORE v2] batch_count

        # # [PATCH TOOLTIP MORE v2] batch_seed

        # # [PATCH TOOLTIP MORE v2] batch_base_year

        self._add_international_data_section(frm, row=3, prefix="batch")

    def _build_single_international_tab(self) -> None:
        frm = self.single_international_body
        for c in range(2):
            frm.columnconfigure(c, weight=1)
        # [INTL_TOGGLE_VARS_INIT_V3_SINGLE]
        if not hasattr(self, "single_intl_show_files"):
            self.single_intl_show_files = tk.BooleanVar(value=False)
        if not hasattr(self, "single_intl_show_gen"):
            self.single_intl_show_gen = tk.BooleanVar(value=False)


        # Mirrored file inputs on International Data tab (synced with Other/Details)
        paths = ttk.LabelFrame(frm, text="File inputs")
        paths.grid(row=1, column=0, sticky="ew", padx=8, pady=(0, 8))
        paths.columnconfigure(1, weight=1)
        self.single_international_paths_frame = paths

        def row_file(r, label, var, is_save=False):
            ttk.Label(paths, text=label).grid(row=r, column=0, sticky="w", padx=(8, 6), pady=6)
            ttk.Entry(paths, textvariable=var).grid(row=r, column=1, sticky="ew", padx=(0, 6), pady=6)
            if is_save:
                ttk.Button(paths, text="Browse…", command=lambda: self._pick_save_xml(var)).grid(row=r, column=2, sticky="ew", padx=(0, 8), pady=6)
            else:
                ttk.Button(paths, text="Browse…", command=lambda: self._pick_open_file(var)).grid(row=r, column=2, sticky="ew", padx=(0, 8), pady=6)

        row_file(0, "master_library.csv:", self.single_clubs, is_save=False)
        row_file(1, "Male first names CSV:", self.single_first, is_save=False)
        row_file(2, "Female first names CSV:", self.single_female_first, is_save=False)
        row_file(3, "Common names CSV:", self.single_common_names, is_save=False)
        row_file(4, "Surnames CSV:", self.single_surn, is_save=False)
        row_file(5, "Output XML:", self.single_out, is_save=True)
        row_file(6, "Generator script:", self.single_script, is_save=False)
        row_file(7, "Region mapping CSV (placeholder):", self.single_region_map_csv, is_save=False)


        togg = ttk.Frame(frm)
        togg.grid(row=0, column=0, sticky="e", padx=8, pady=(0, 8))

        def _apply_intl_tab_vis():
            try:
                (paths.grid if getattr(self, "single_intl_show_files").get() else paths.grid_remove)()
            except Exception:
                pass
            try:
                (genf.grid if getattr(self, "single_intl_show_gen").get() else genf.grid_remove)()
            except Exception:
                pass

        ttk.Checkbutton(
            togg,
            text="Show file inputs",
            variable=getattr(self, "single_intl_show_files"),
            command=_apply_intl_tab_vis,
        ).grid(row=0, column=0, sticky="w", padx=(0, 10))

        ttk.Checkbutton(
            togg,
            text="Show generation settings",
            variable=getattr(self, "single_intl_show_gen"),
            command=_apply_intl_tab_vis,
        ).grid(row=0, column=1, sticky="w")

        _apply_intl_tab_vis()

        for c in range(4):
            pass  # [AUTO_EMPTY_FOR_FIX]

        self._add_international_data_section(frm, row=3, prefix="single")


    def _append_international_cli_args(self, extra: list[str], prefix: str) -> None:
        """Append International Data tab args + Other Nation Caps payloads."""
        def _gv(name: str, default: str = ""):
            v = getattr(self, name, None)
            if v is None:
                return default
            try:
                return v.get()
            except Exception:
                return default
        # Main fields: Random -> -2 (generator auto); Custom -> explicit; Don't set -> omit-field
        int_fields = [
            ("international_apps", "--international_apps"),
            ("international_goals", "--international_goals"),
            ("u21_international_apps", "--u21_international_apps"),
            ("u21_international_goals", "--u21_international_goals"),
        ]
        for key, flag in int_fields:
            mode = str(_gv(f"{prefix}_intl_{key}_mode", "none") or "none").strip().lower()
            val = str(_gv(f"{prefix}_intl_{key}_value", "") or "").strip()
            if mode == "none":
                extra.extend(["--omit-field", key])
            elif mode == "custom":
                if val == "":
                    raise ValueError(f"{key} is Custom but blank")
                extra.extend([flag, str(int(val))])
            else:
                extra.extend([flag, "-2"])
        # Dates/nations: Custom passes string; Don't set uses omit-field; Random -> omit (generator fills when caps>0)
        str_fields = [
            ("international_debut_date", "--international_debut_date"),
            ("international_debut_against", "--international_debut_against"),
            ("first_international_goal_date", "--first_international_goal_date"),
            ("first_international_goal_against", "--first_international_goal_against"),
        ]
        for key, flag in str_fields:
            mode = str(_gv(f"{prefix}_intl_{key}_mode", "none") or "none").strip().lower()
            val = str(_gv(f"{prefix}_intl_{key}_value", "") or "").strip()
            if mode == "none":
                extra.extend(["--omit-field", key])
            elif mode == "custom" and val:
                extra.extend([flag, val])
        # Other Nation Caps lists: pass JSON payloads (generator accepts compatibility flags)
        for list_key, flag in [
            ("other_nation_caps", "--other_nation_caps_json"),
            ("other_nation_youth_caps", "--other_nation_youth_caps_json"),
        ]:
            mode = str(_gv(f"{prefix}_{list_key}_mode", "none") or "none").strip().lower()
            items = getattr(self, f"{prefix}_{list_key}_items", []) or []
            if mode == "none":
                extra.extend(["--omit-field", list_key])
            elif mode == "custom":
                try:
                    payload = json.dumps(items, ensure_ascii=True)
                except Exception:
                    payload = "[]"
                extra.extend([flag, payload])
            else:
                # Random: let generator decide; if it doesn't implement yet, harmless.
                extra.extend([flag, "__RANDOM__"])

