# -*- coding: utf-8 -*-
# Person Data sub-tabs (FM Editor-style scaffold)
# Auto-generated by fm26_patch_gui_person_data_fix_and_use_gui_py_v1.py
from __future__ import annotations

import json
import tkinter as tk
from tkinter import ttk


class PersonDataSubtabMixin:
    """Adds 'Person Data' UI for Player Batch/Single tabs."""

    def _pd_sv(self, name: str, default: str = "") -> tk.StringVar:
        v = getattr(self, name, None)
        if v is None:
            v = tk.StringVar(value=default)
            setattr(self, name, v)
        return v

    def _build_person_data_tab_common(self, frm: ttk.Frame, *, prefix: str) -> None:
        try:
            frm.columnconfigure(0, weight=1)
            frm.rowconfigure(0, weight=1)
        except Exception:
            pass

        subnb = ttk.Notebook(frm)
        subnb.grid(row=0, column=0, sticky="nsew", padx=8, pady=8)
        setattr(self, f"{prefix}_person_subnotebook", subnb)

        tabs = {}
        for key, label in (
            ("attributes", "Attributes"),
            ("retirements", "Retirements"),
            ("languages", "Languages"),
            ("days", "Days At Club/In Nation"),
            ("career", "Career Plans"),
        ):
            t = ttk.Frame(subnb)
            t.columnconfigure(0, weight=1)
            subnb.add(t, text=label)
            tabs[key] = t
            setattr(self, f"{prefix}_person_{key}_tab", t)

        # Attributes tab
        attr_tab = tabs["attributes"]
        attr_tab.columnconfigure(0, weight=1)

        header = ttk.Label(
            attr_tab,
            text=(
                "Person Data ▸ Attributes (FM Editor-style)\n\n"
                "This is a UI scaffold. Values are stored in the GUI state now;\n"
                "XML/CLI wiring can be added later once the exact FM property IDs are confirmed."
            ),
            justify="left",
            foreground="#444",
            wraplength=960,
        )
        header.grid(row=0, column=0, sticky="w", padx=8, pady=(6, 10))

        box = ttk.LabelFrame(attr_tab, text="Attributes (1–20)")
        box.grid(row=1, column=0, sticky="ew", padx=8, pady=(0, 10))
        for c in range(6):
            box.columnconfigure(c, weight=0)
        box.columnconfigure(5, weight=1)

        ttk.Label(box, text="Attribute").grid(row=0, column=0, sticky="w", padx=8, pady=(6, 4))
        ttk.Label(box, text="Mode").grid(row=0, column=1, sticky="w", padx=8, pady=(6, 4))
        ttk.Label(box, text="Fixed").grid(row=0, column=2, sticky="w", padx=8, pady=(6, 4))
        ttk.Label(box, text="Min").grid(row=0, column=3, sticky="w", padx=8, pady=(6, 4))
        ttk.Label(box, text="Max").grid(row=0, column=4, sticky="w", padx=8, pady=(6, 4))

        attrs = [
            ("adaptability", "Adaptability"),
            ("ambition", "Ambition"),
            ("controversy", "Controversy"),
            ("loyalty", "Loyalty"),
            ("pressure", "Pressure"),
            ("professionalism", "Professionalism"),
            ("sportsmanship", "Sportsmanship"),
            ("temperament", "Temperament"),
        ]

        def mk_attr_row(r: int, key: str, label: str) -> None:
            mode = self._pd_sv(f"{prefix}_person_attr_{key}_mode", "random")
            fixed = self._pd_sv(f"{prefix}_person_attr_{key}_fixed", "")
            vmin = self._pd_sv(f"{prefix}_person_attr_{key}_min", "")
            vmax = self._pd_sv(f"{prefix}_person_attr_{key}_max", "")

            ttk.Label(box, text=label).grid(row=r, column=0, sticky="w", padx=8, pady=3)
            ttk.Combobox(box, textvariable=mode, values=["random", "fixed", "range", "none"], width=10, state="normal").grid(row=r, column=1, sticky="w", padx=8, pady=3)

            sp_fixed = ttk.Spinbox(box, from_=1, to=20, textvariable=fixed, width=6)
            sp_fixed.grid(row=r, column=2, sticky="w", padx=8, pady=3)
            sp_min = ttk.Spinbox(box, from_=1, to=20, textvariable=vmin, width=6)
            sp_min.grid(row=r, column=3, sticky="w", padx=8, pady=3)
            sp_max = ttk.Spinbox(box, from_=1, to=20, textvariable=vmax, width=6)
            sp_max.grid(row=r, column=4, sticky="w", padx=8, pady=3)

            try:
                if hasattr(self, "_bind_mode_enable"):
                    self._bind_mode_enable(mode, "fixed", [sp_fixed], clear_on_random=True)
                    self._bind_mode_enable(mode, "range", [sp_min, sp_max], clear_on_random=True)
            except Exception:
                pass

        rr = 1
        for key, label in attrs:
            mk_attr_row(rr, key, label)
            rr += 1

        ttk.Label(
            box,
            text=(
                "Modes:\n"
                "  random = generator chooses\n"
                "  fixed = use Fixed\n"
                "  range = random between Min/Max\n"
                "  none = do not set (omit)"
            ),
            justify="left",
            foreground="#444",
        ).grid(row=rr, column=0, columnspan=6, sticky="w", padx=8, pady=(6, 8))

        # Job preferences (0–20)
        jp = ttk.LabelFrame(attr_tab, text="Job Preferences (0–20)")
        jp.grid(row=2, column=0, sticky="ew", padx=8, pady=(0, 10))
        jp.columnconfigure(2, weight=1)

        roles = [
            "Manager",
            "Assistant Manager",
            "Coach",
            "Fitness Coach",
            "Goalkeeping Coach",
            "Set Piece Coach",
            "Head of Youth Development",
            "Director of Football",
            "Technical Director",
            "Scout",
        ]

        ttk.Label(jp, text="Role").grid(row=0, column=0, sticky="w", padx=8, pady=(6, 4))
        ttk.Label(jp, text="Value").grid(row=0, column=1, sticky="w", padx=8, pady=(6, 4))

        prefs = getattr(self, f"{prefix}_job_pref_vars", None)
        if prefs is None:
            prefs = {}
            setattr(self, f"{prefix}_job_pref_vars", prefs)

        for i, role in enumerate(roles, start=1):
            v = prefs.get(role)
            if v is None:
                v = tk.StringVar(value="0")
                prefs[role] = v
            ttk.Label(jp, text=role).grid(row=i, column=0, sticky="w", padx=8, pady=2)
            ttk.Spinbox(jp, from_=0, to=20, textvariable=v, width=6).grid(row=i, column=1, sticky="w", padx=8, pady=2)

        btns = ttk.Frame(jp)
        btns.grid(row=len(roles) + 1, column=0, columnspan=3, sticky="w", padx=8, pady=(8, 8))

        def collect_jobprefs() -> dict:
            out = {}
            for r, vv in prefs.items():
                try:
                    out[r] = int(str(vv.get() or "0").strip())
                except Exception:
                    out[r] = 0
            return out

        def apply_jobprefs(d: dict) -> None:
            for r, vv in prefs.items():
                if r in d:
                    try:
                        vv.set(str(int(d[r])))
                    except Exception:
                        pass

        def copy_jobprefs() -> None:
            payload = collect_jobprefs()
            setattr(self, f"{prefix}_job_pref_clipboard", payload)
            try:
                self.clipboard_clear()
                self.clipboard_append(json.dumps(payload, ensure_ascii=True))
            except Exception:
                pass

        def paste_jobprefs() -> None:
            payload = getattr(self, f"{prefix}_job_pref_clipboard", None)
            if not isinstance(payload, dict):
                try:
                    payload = json.loads(self.clipboard_get())
                except Exception:
                    payload = None
            if isinstance(payload, dict):
                apply_jobprefs(payload)

        ttk.Button(btns, text="Copy", command=copy_jobprefs).pack(side="left", padx=(0, 6))
        ttk.Button(btns, text="Paste", command=paste_jobprefs).pack(side="left")

        # Retirements tab (placeholder)
        ttk.Label(
            tabs["retirements"],
            text="Retirements (scaffold)\n\nAdd retirement flags/dates here next.",
            padding=16,
            foreground="#444",
            justify="left",
            wraplength=960,
        ).pack(anchor="w")

        # Languages tab (placeholder)
        ttk.Label(
            tabs["languages"],
            text="Languages (scaffold)\n\nAdd spoken languages + proficiency editor here next.",
            padding=16,
            foreground="#444",
            justify="left",
            wraplength=960,
        ).pack(anchor="w")

        # Days At Club/In Nation tab (wired to existing vars with safe defaults)
        days_tab = tabs["days"]
        days_tab.columnconfigure(0, weight=1)

        boxd = ttk.LabelFrame(days_tab, text="Dates (used to compute days at club / in nation)")
        boxd.grid(row=0, column=0, sticky="ew", padx=8, pady=8)
        boxd.columnconfigure(5, weight=1)

        moved_mode = self._pd_sv(f"{prefix}_moved_to_nation_mode", "dob")
        moved_date = self._pd_sv(f"{prefix}_moved_to_nation_date", "")
        joined_mode = self._pd_sv(f"{prefix}_joined_club_mode", "auto")
        joined_date = self._pd_sv(f"{prefix}_joined_club_date", "")

        ttk.Label(boxd, text="Moved to nation date").grid(row=0, column=0, sticky="w", padx=8, pady=6)
        ttk.Combobox(boxd, textvariable=moved_mode, values=["dob", "fixed"], width=10, state="normal").grid(row=0, column=1, sticky="w", padx=8, pady=6)
        ttk.Entry(boxd, textvariable=moved_date, width=14).grid(row=0, column=2, sticky="w", padx=8, pady=6)
        ttk.Label(boxd, text="YYYY-MM-DD", foreground="#444").grid(row=0, column=3, sticky="w", padx=8, pady=6)

        ttk.Label(boxd, text="Joined club date").grid(row=1, column=0, sticky="w", padx=8, pady=6)
        ttk.Combobox(boxd, textvariable=joined_mode, values=["auto", "fixed"], width=10, state="normal").grid(row=1, column=1, sticky="w", padx=8, pady=6)
        ttk.Entry(boxd, textvariable=joined_date, width=14).grid(row=1, column=2, sticky="w", padx=8, pady=6)
        ttk.Label(boxd, text="YYYY-MM-DD", foreground="#444").grid(row=1, column=3, sticky="w", padx=8, pady=6)

        ttk.Label(
            boxd,
            text="Note: these are the same overrides used by the generator; this tab just exposes them FM-style.",
            foreground="#444",
            justify="left",
        ).grid(row=2, column=0, columnspan=6, sticky="w", padx=8, pady=(6, 8))

        # Career Plans tab (placeholder)
        ttk.Label(
            tabs["career"],
            text="Career Plans (scaffold)\n\nAdd career plan fields here next.",
            padding=16,
            foreground="#444",
            justify="left",
            wraplength=960,
        ).pack(anchor="w")

    def _build_batch_person_data_tab(self) -> None:
        self._build_person_data_tab_common(self.batch_person_data_body, prefix="batch")

    def _build_single_person_data_tab(self) -> None:
        self._build_person_data_tab_common(self.single_person_data_body, prefix="single")
