# -*- coding: utf-8 -*-
# Player Data sub-tabs (FM Editor-style scaffold)
# Auto-generated by fm26_patch_gui_add_player_data_tabs_v1b.py
from __future__ import annotations

import tkinter as tk
from tkinter import ttk


class PlayerDataSubtabMixin:
    "Adds Player Data UI for Player Batch/Single tabs."

    def _pl_sv(self, name: str, default: str = "") -> tk.StringVar:
        v = getattr(self, name, None)
        if v is None:
            v = tk.StringVar(value=default)
            setattr(self, name, v)
        return v

    def _pl_bv(self, name: str, default: bool = False) -> tk.BooleanVar:
        v = getattr(self, name, None)
        if v is None:
            v = tk.BooleanVar(value=bool(default))
            setattr(self, name, v)
        return v

    def _build_player_data_tab_common(self, frm: ttk.Frame, *, prefix: str) -> None:
        try:
            frm.columnconfigure(0, weight=1)
            frm.rowconfigure(0, weight=1)
        except Exception:
            pass

        subnb = ttk.Notebook(frm)
        subnb.grid(row=0, column=0, sticky="nsew", padx=8, pady=8)
        setattr(self, f"{prefix}_player_subnotebook", subnb)

        tab_defs = [
            ("general", "General"),
            ("positions", "Positions"),
            ("ip_role", "IP Role Scores"),
            ("oop_role", "OOP Role Scores"),
            ("pos_scores", "Position Scores"),
            ("ca_dep", "Current Ability-Dependent Attributes"),
            ("mental", "Mental Attributes"),
            ("physical", "Physical Attributes"),
            ("technical", "Technical Attributes"),
            ("gk", "Goalkeeping Attributes"),
            ("all_attr", "All Attributes"),
            ("weightings", "Weightings"),
        ]

        tabs = {}
        for key, label in tab_defs:
            t = ttk.Frame(subnb)
            t.columnconfigure(0, weight=1)
            subnb.add(t, text=label)
            tabs[key] = t
            setattr(self, f"{prefix}_player_{key}_tab", t)

        # ---------------- General ----------------
        g = tabs["general"]
        g.columnconfigure(0, weight=1)

        ttk.Label(
            g,
            text=(
                "Player Data ▸ General (FM Editor-style)\n\n"
                "This is a UI scaffold. Values are stored in the GUI state now;\n"
                "XML/CLI wiring can be added later once the exact FM property IDs are confirmed."
            ),
            justify="left",
            foreground="#444",
            wraplength=960,
        ).grid(row=0, column=0, sticky="w", padx=8, pady=(6, 10))

        box = ttk.LabelFrame(g, text="General")
        box.grid(row=1, column=0, sticky="ew", padx=8, pady=(0, 10))
        for c in range(10):
            box.columnconfigure(c, weight=0)
        box.columnconfigure(9, weight=1)

        r = 0
        ttk.Label(box, text="Shirt Name").grid(row=r, column=0, sticky="w", padx=8, pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_shirt_name", ""), width=28).grid(
            row=r, column=1, columnspan=3, sticky="w", padx=8, pady=6
        )
        r += 1

        # CA
        ttk.Label(box, text="Current Ability (CA)").grid(row=r, column=0, sticky="w", padx=8, pady=6)
        ca_mode = self._pl_sv(f"{prefix}_pd_ca_mode", "range")  # random|fixed|range|none
        ttk.Combobox(box, textvariable=ca_mode, values=["range", "fixed", "random", "none"], width=10).grid(
            row=r, column=1, sticky="w", padx=8, pady=6
        )
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_ca_fixed", ""), width=8).grid(
            row=r, column=2, sticky="w", padx=8, pady=6
        )
        ttk.Label(box, text="min").grid(row=r, column=3, sticky="w", padx=(16, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_ca_min", ""), width=6).grid(
            row=r, column=4, sticky="w", padx=4, pady=6
        )
        ttk.Label(box, text="max").grid(row=r, column=5, sticky="w", padx=(16, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_ca_max", ""), width=6).grid(
            row=r, column=6, sticky="w", padx=4, pady=6
        )
        r += 1

        # PA
        ttk.Label(box, text="Potential Ability (PA)").grid(row=r, column=0, sticky="w", padx=8, pady=6)
        pa_mode = self._pl_sv(f"{prefix}_pd_pa_mode", "range")
        ttk.Combobox(box, textvariable=pa_mode, values=["range", "fixed", "random", "none"], width=10).grid(
            row=r, column=1, sticky="w", padx=8, pady=6
        )
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_pa_fixed", ""), width=8).grid(
            row=r, column=2, sticky="w", padx=8, pady=6
        )
        ttk.Label(box, text="min").grid(row=r, column=3, sticky="w", padx=(16, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_pa_min", ""), width=6).grid(
            row=r, column=4, sticky="w", padx=4, pady=6
        )
        ttk.Label(box, text="max").grid(row=r, column=5, sticky="w", padx=(16, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_pa_max", ""), width=6).grid(
            row=r, column=6, sticky="w", padx=4, pady=6
        )
        r += 1

        # Reputation
        ttk.Label(box, text="Reputation (0–200)").grid(row=r, column=0, sticky="w", padx=8, pady=6)
        rep_mode = self._pl_sv(f"{prefix}_pd_rep_mode", "range")  # fixed|range|none
        ttk.Combobox(box, textvariable=rep_mode, values=["range", "fixed", "none"], width=10).grid(
            row=r, column=1, sticky="w", padx=8, pady=6
        )
        ttk.Label(box, text="cur").grid(row=r, column=2, sticky="w", padx=(8, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_rep_current", ""), width=6).grid(
            row=r, column=3, sticky="w", padx=4, pady=6
        )
        ttk.Label(box, text="home").grid(row=r, column=4, sticky="w", padx=(16, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_rep_home", ""), width=6).grid(
            row=r, column=5, sticky="w", padx=4, pady=6
        )
        ttk.Label(box, text="world").grid(row=r, column=6, sticky="w", padx=(16, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_rep_world", ""), width=6).grid(
            row=r, column=7, sticky="w", padx=4, pady=6
        )
        r += 1

        # Feet
        ttk.Label(box, text="Left Foot (1–20)").grid(row=r, column=0, sticky="w", padx=8, pady=6)
        ttk.Spinbox(box, from_=1, to=20, textvariable=self._pl_sv(f"{prefix}_pd_left_foot", ""), width=6).grid(
            row=r, column=1, sticky="w", padx=8, pady=6
        )
        ttk.Label(box, text="Right Foot (1–20)").grid(row=r, column=2, sticky="w", padx=8, pady=6)
        ttk.Spinbox(box, from_=1, to=20, textvariable=self._pl_sv(f"{prefix}_pd_right_foot", ""), width=6).grid(
            row=r, column=3, sticky="w", padx=8, pady=6
        )
        r += 1

        # Work permit
        wp = self._pl_bv(f"{prefix}_pd_work_permit", False)
        ttk.Checkbutton(box, text="Has Work Permit", variable=wp).grid(row=r, column=0, sticky="w", padx=8, pady=(2, 8))
        r += 1

        # Transfer value
        ttk.Label(box, text="Transfer Value").grid(row=r, column=0, sticky="w", padx=8, pady=6)
        tv_mode = self._pl_sv(f"{prefix}_pd_tv_mode", "auto")  # auto|fixed|range|none
        ttk.Combobox(box, textvariable=tv_mode, values=["auto", "fixed", "range", "none"], width=10).grid(
            row=r, column=1, sticky="w", padx=8, pady=6
        )
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_tv_fixed", ""), width=12).grid(
            row=r, column=2, sticky="w", padx=8, pady=6
        )
        ttk.Label(box, text="min").grid(row=r, column=3, sticky="w", padx=(16, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_tv_min", ""), width=10).grid(
            row=r, column=4, sticky="w", padx=4, pady=6
        )
        ttk.Label(box, text="max").grid(row=r, column=5, sticky="w", padx=(16, 4), pady=6)
        ttk.Entry(box, textvariable=self._pl_sv(f"{prefix}_pd_tv_max", ""), width=10).grid(
            row=r, column=6, sticky="w", padx=4, pady=6
        )

        # ---------------- Scaffold for remaining tabs ----------------
        for key, label in tab_defs:
            if key == "general":
                continue
            ttk.Label(
                tabs[key],
                text=f"{label} (scaffold)\n\nAdd UI + property mapping here next.",
                padding=16,
                foreground="#444",
                justify="left",
                wraplength=960,
            ).pack(anchor="w")

    def _build_batch_player_data_tab(self) -> None:
        self._build_player_data_tab_common(self.batch_player_data_body, prefix="batch")

    def _build_single_player_data_tab(self) -> None:
        self._build_player_data_tab_common(self.single_player_data_body, prefix="single")
