# -*- coding: utf-8 -*-
from __future__ import annotations

# CLI entrypoint (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_cli_entry_v1.py

import argparse
import datetime as dt
import sys
from typing import List, Optional


def main(argv=None, gen_mod=None) -> int:
        # --- injected: bind generator module + required symbols ---
        import sys as _sys
        if gen_mod is None:
            gen_mod = _sys.modules.get("__main__")
        g = gen_mod

        # Pull commonly-used symbols from generator module into locals so the extracted body is unchanged.
        generate_players_xml = getattr(g, "generate_players_xml")
        resolve_nationality_info = getattr(g, "resolve_nationality_info")
        nationality_info_mapping_lines = getattr(g, "nationality_info_mapping_lines")

        _resolve_output_xml_path = getattr(g, "_resolve_output_xml_path")
        _parse_ymd = getattr(g, "_parse_ymd")

        POS_PROPS = getattr(g, "POS_PROPS")
        ALL_POS = getattr(g, "ALL_POS")
        DEFAULT_VERSION = getattr(g, "DEFAULT_VERSION")

        # Optional modules referenced by the CLI (safe if missing in some builds)
        _pos = getattr(g, "_pos", None)
        _ids = getattr(g, "_ids", None)

        # --- end injected preamble ---
    if argv is None:
        argv = sys.argv[1:]
    if any(a in ('--list_nationality_info', '--list-nationality-info') for a in argv):
        for line in nationality_info_mapping_lines():
            print(line)
        return 0

    ap = argparse.ArgumentParser()
    ap.add_argument("--master_library", "--library", dest="library_csv", required=True)
    ap.add_argument("--count", type=int, required=True)
    ap.add_argument("--output", required=True)
    ap.add_argument("--append", action="store_true")
    ap.add_argument("--start_index", type=int, default=0)
    ap.add_argument("--age_min", type=int, default=14)
    ap.add_argument("--age_max", type=int, default=16)
    ap.add_argument("--ca_min", type=int, default=20)
    ap.add_argument("--ca_max", type=int, default=160)
    ap.add_argument("--pa_min", type=int, default=80)
    ap.add_argument("--pa_max", type=int, default=200)
    ap.add_argument("--base_year", type=int, default=2026)
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--id_registry_mode", choices=["auto", "off"], default="auto")
    ap.add_argument("--id_registry_path", default=None)
    ap.add_argument("--id_namespace_salt", default=None)
    ap.add_argument("--omit-field", action="append", default=[], help="Field key to omit entirely (repeatable). Used by GUI Don\'t set modes.")
    ap.add_argument("--xml_comments", action="store_true", default=False, help="Include XML comments (larger files). Default: off")
    ap.add_argument("--version", type=int, default=DEFAULT_VERSION)

    ap.add_argument("--dob", default="")
    ap.add_argument("--dob_start", default="")
    ap.add_argument("--dob_end", default="")
    ap.add_argument("--moved_to_nation_date", default="", help="Override date moved to nation (YYYY-MM-DD). Default: DOB")
    ap.add_argument("--joined_club_date", default="", help="Override joined club date (YYYY-MM-DD). Default: base_year-07-01")
    ap.add_argument("--contract_expires_date", default="", help="Override contract expiry date (YYYY-MM-DD). Default: base_year+3-06-30")
    ap.add_argument("--date_last_signed", default="", help="Override date last contract signed (YYYY-MM-DD). Default: joined club date")
    ap.add_argument("--last_contract_signed_date", default="", help="Alias of --date_last_signed")
    ap.add_argument("--squad_status", type=int, default=None, help="Override squad status integer (FM enum). Default: 9")

    ap.add_argument("--person_type_value", type=int, default=None, help="1 = Non-Player, 2 = Player")
    ap.add_argument("--gender_value", type=int, default=None, help="0 = Male, 1 = Female")
    ap.add_argument("--ethnicity_value", type=int, default=None, help="FM ethnicity mapping (-1..10)")
    ap.add_argument("--hair_colour_value", type=int, default=None, help="FM hair colour mapping (0..6)")
    ap.add_argument("--hair_length_value", type=int, default=None, help="FM hair length mapping (0..3)")
    ap.add_argument("--skin_tone_value", type=int, default=None, help="FM skin tone mapping (-1..19; Unknown=-1, Skin Tone 1=0 ... Skin Tone 20=19)")
    ap.add_argument("--body_type_value", type=int, default=None, help="FM body type mapping (1..5) [1=Ectomorph, 2=Ecto-Mesomorph, 3=Mesomorph, 4=Meso-Endomorph, 5=Endomorph]")

    ap.add_argument("--height", type=int, default=0)
    ap.add_argument("--height_min", type=int, default=150)
    ap.add_argument("--height_max", type=int, default=210)

    ap.add_argument("--feet", default="random", choices=["random", "left_only", "left", "right_only", "right", "both"])

    # Wage / Reputation / Transfer value
    ap.add_argument("--wage", type=int, default=0)
    ap.add_argument("--wage_min", type=int, default=30)
    ap.add_argument("--wage_max", type=int, default=80)

    ap.add_argument("--rep_current", type=int, default=-1)
    ap.add_argument("--rep_home", type=int, default=-1)
    ap.add_argument("--rep_world", type=int, default=-1)
    ap.add_argument("--rep_min", type=int, default=0)
    ap.add_argument("--rep_max", type=int, default=200)

    ap.add_argument("--transfer_mode", default="auto", choices=["auto", "fixed", "range"])
    ap.add_argument("--transfer_value", type=int, default=0)
    ap.add_argument("--transfer_min", type=int, default=0)
    ap.add_argument("--transfer_max", type=int, default=0)

    ap.add_argument("--left_foot", type=int, default=0)
    ap.add_argument("--right_foot", type=int, default=0)

    # fixed club/city/nation
    ap.add_argument("--club_dbid", type=int, default=0)
    ap.add_argument("--club_large", type=int, default=0)
    ap.add_argument("--club_assign_pct", type=int, default=100, help="Percent of generated people who get a club assignment when club is set (random or fixed). 0=all free agents, 100=all have clubs.")
    ap.add_argument("--city_dbid", type=int, default=0)
    ap.add_argument("--city_large", type=int, default=0)
    ap.add_argument("--nation_dbid", type=int, default=0)
    ap.add_argument("--nation_large", type=int, default=0)

    # legacy positions (still supported)
    ap.add_argument("--positions", default="")

    # new positions
    ap.add_argument("--pos_primary", default="")
    ap.add_argument("--pos_20", default="")
    ap.add_argument("--pos_all_outfield_20", action="store_true")
    ap.add_argument("--pos_dev", default="")
    ap.add_argument("--pos_dev_mode", default="random", choices=["random", "fixed", "range"])
    ap.add_argument("--pos_dev_value", type=int, default=0)
    ap.add_argument("--pos_dev_min", type=int, default=2)
    ap.add_argument("--pos_dev_max", type=int, default=19)

    ap.add_argument("--auto_dev_chance", type=float, default=0.15)
    ap.add_argument("--pos_primary_dist", default="15,35,35,15")
    ap.add_argument("--pos_n20_dist", default="39,18,13,11,8,5.5,3.6,1.4,0.5")

    ap.add_argument("--nationality_info_value", type=int, default=85)
    ap.add_argument("--nationality_info", default="", help="Nationality info by name or numeric value (e.g. 'Born In Nation' or 85). Overrides --nationality_info_value if set")
    ap.add_argument("--second_nation", action="append", default=[], help="Repeatable second nation entry. Format: Nation or Nation|Nationality Info label/value")
    ap.add_argument("--declared_for_youth_nation", default="", help="Nation name for separate Declared For Nation At Youth Level field (property 1349411961)")
    ap.add_argument("--list_nationality_info", action="store_true", help="Print nationality info mapping (value -> name) and exit")
    ap.add_argument("--international_retirement", action="store_true", help="Set International Retirement = true")
    ap.add_argument("--international_retirement_date", default="", help="Set International Retirement Date (YYYY-MM-DD)")
    ap.add_argument("--retiring_after_spell_current_club", action="store_true", help="Set Retiring After Spell At Current Club = true")
    ap.add_argument("--international_apps", type=int, default=None, help="International appearances (property 1349083504)")
    ap.add_argument("--international_goals", type=int, default=None, help="International goals (property 1349085036)")
    ap.add_argument("--u21_international_apps", type=int, default=None, help="U21 International appearances (property 1349871969)")
    ap.add_argument("--u21_international_goals", type=int, default=None, help="U21 International goals (property 1349871975)")
    ap.add_argument("--international_debut_date", default="", help="International debut date (YYYY-MM-DD)")
    ap.add_argument("--international_debut_against", default="", help="International debut against nation name")
    ap.add_argument("--u21_international_debut_date", default="", help="U21 International debut date (YYYY-MM-DD)")
    ap.add_argument("--u21_international_debut_against", default="", help="U21 International debut against nation name")
    ap.add_argument("--first_international_goal_date", default="", help="First international goal date (YYYY-MM-DD) [GUI compatibility]")
    ap.add_argument("--first_international_goal_against", default="", help="First international goal against nation name [GUI compatibility]")
    ap.add_argument("--other_nation_caps_json", default="", help="Reserved GUI payload (not yet written to XML; accepted for compatibility)")
    ap.add_argument("--other_nation_youth_caps_json", default="", help="Reserved GUI payload (not yet written to XML; accepted for compatibility)")
    ap.add_argument("--first_names", default="male_first_names.csv")
    ap.add_argument("--female_first_names", default="female_first_names.csv")
    ap.add_argument("--common_names", default="common_names.csv")
    ap.add_argument("--common_name_chance", type=float, default=5.0, help="Chance of using common name CSV (0-1 or 0-100); default 5")
    # [PATCH SETTINGS PACK v3a] knobs
    ap.add_argument("--name_local_bias", type=float, default=85.0, help="Local-name bias (0-1 or 0-100). Default 85")
    ap.add_argument("--female_pct", type=float, default=50.0, help="Percent female when gender random (0-100). Default 50")
    
    ap.add_argument("--extra_nation_pct", type=float, default=5.0, help="Chance of >=1 extra nationality (percent). Default 5")
    ap.add_argument("--extra_nation_third_given_second_pct", type=float, default=30.0, help="Chance of 3rd given 2nd (percent). Default 30")
    ap.add_argument("--extra_nation_fourth_given_third_pct", type=float, default=33.333, help="Chance of 4th given 3rd (percent). Default 33.333")
    ap.add_argument("--extra_nation_fifthplus_given_fourth_pct", type=float, default=10.0, help="Chance of 5+ given 4th (percent). Default 10")
    ap.add_argument("--extra_nation_chain_pct", type=float, default=20.0, help="Chance to keep adding beyond 5 (percent). Default 20")
    ap.add_argument("--extra_nation_max", type=int, default=8, help="Max extra nationalities. Default 8")
    
    ap.add_argument("--appearance_mode", type=str, default="nation", help="nation|global. Default nation")
    ap.add_argument("--appearance_global_ethnicity", type=str, default="0-10", help="Global ethnicity range min-max")
    ap.add_argument("--appearance_global_skin", type=str, default="0-19", help="Global skin range min-max")
    ap.add_argument("--appearance_global_hair_colour", type=str, default="0-6", help="Global hair colour range min-max")
    ap.add_argument("--hair_length_weights_male", type=str, default="36,40,18,6", help="Male hair length weights [0,1,2,3]")
    ap.add_argument("--hair_length_weights_female", type=str, default="8,20,34,38", help="Female hair length weights [0,1,2,3]")
    ap.add_argument("--body_type_weights", type=str, default="95,4,1", help="Body type weights [1-3 group, 4, 5]")
    
    ap.add_argument("--intl_play_prob_mult", type=float, default=1.0, help="Multiplier for auto international play probability. Default 1.0")
    ap.add_argument("--intl_opponent_mode", type=str, default="random", help="random|similar. Default random")
    ap.add_argument("--intl_opponent_similarity", type=float, default=0.75, help="0..1 similarity weighting. Default 0.75")
    
    ap.add_argument("--surnames", default="surnames.csv")
    ap.add_argument("--first_name_text", default="", help="Fixed first name (optional; skips first names CSV if set)")
    ap.add_argument("--second_name_text", default="", help="Fixed second/surname (optional; skips surnames CSV if set)")
    ap.add_argument("--last_name_text", default="", help="Alias for second/surname (optional; compatibility)")
    ap.add_argument("--common_name_text", default="", help="Fixed common name (optional)")
    ap.add_argument("--full_name_text", default="", help="Alias for common name (optional)")

    _argv_for_parse = list(sys.argv[1:] if argv is None else argv)
    _nat_info_explicit = any(
        (a == "--nationality_info")
        or str(a).startswith("--nationality_info=")
        or (a == "--nationality_info_value")
        or str(a).startswith("--nationality_info_value=")
        for a in _argv_for_parse
    )
    args = ap.parse_args(_argv_for_parse)

    # Defensive init (prevents UnboundLocalError in mixed GUI/CLI builds)
    resolved_last_name_text = ""
    resolved_full_name_text = ""

    # [PATCH SETTINGS PACK v3a] apply args to module defaults
    global _NAME_LOCAL_BIAS, _FEMALE_PCT
    global _EXTRA_NATION_P2, _EXTRA_NATION_P3_GIVEN_P2, _EXTRA_NATION_P4_GIVEN_P3, _EXTRA_NATION_P5PLUS_GIVEN_P4, _EXTRA_NATION_CHAIN_P, _EXTRA_NATION_MAX
    global _APPEARANCE_MODE, _GLOBAL_ETH_RANGE, _GLOBAL_SKIN_RANGE, _GLOBAL_HAIR_RANGE, _HAIR_LEN_WEIGHTS_MALE, _HAIR_LEN_WEIGHTS_FEMALE, _BODY_TYPE_W123, _BODY_TYPE_W4, _BODY_TYPE_W5
    global _INTL_PLAY_PROB_MULT, _INTL_OPPONENT_MODE, _INTL_OPPONENT_SIMILARITY
    
    def _pct_to_prob(v, default_prob: float) -> float:
        try:
            x = float(v)
        except Exception:
            return float(default_prob)
        if x > 1.0:
            x = x / 100.0
        if x < 0.0:
            x = 0.0
        if x > 1.0:
            x = 1.0
        return float(x)
    
    def _pct_0_100(v, default_pct: float) -> float:
        try:
            x = float(v)
        except Exception:
            return float(default_pct)
        if x < 0.0:
            x = 0.0
        if x > 100.0:
            x = 100.0
        return float(x)
    
    def _parse_range(s: str, lo: int, hi: int) -> tuple[int, int]:
        raw = str(s or "").strip()
        if "-" in raw:
            a, b = raw.split("-", 1)
        else:
            a, b = raw, raw
        try:
            x = int(a.strip())
        except Exception:
            x = lo
        try:
            y = int(b.strip())
        except Exception:
            y = hi
        if x > y:
            x, y = y, x
        if x < lo:
            x = lo
        if y > hi:
            y = hi
        return (x, y)
    
    def _parse_w4(s: str, default: tuple[int, int, int, int]) -> tuple[int, int, int, int]:
        parts = [p.strip() for p in str(s or "").split(",") if p.strip()]
        if len(parts) != 4:
            return default
        out = []
        for p in parts:
            try:
                out.append(int(float(p)))
            except Exception:
                out.append(0)
        return (out[0], out[1], out[2], out[3])
    
    def _parse_w3(s: str, default: tuple[float, float, float]) -> tuple[float, float, float]:
        parts = [p.strip() for p in str(s or "").split(",") if p.strip()]
        if len(parts) != 3:
            return default
        out = []
        for p in parts:
            try:
                out.append(float(p))
            except Exception:
                out.append(0.0)
        return (out[0], out[1], out[2])
    
    _NAME_LOCAL_BIAS = _pct_to_prob(getattr(args, "name_local_bias", 85.0), 0.85)
    _FEMALE_PCT = _pct_0_100(getattr(args, "female_pct", 50.0), 50.0)
    
    _EXTRA_NATION_P2 = _pct_to_prob(getattr(args, "extra_nation_pct", 5.0), 0.05)
    _EXTRA_NATION_P3_GIVEN_P2 = _pct_to_prob(getattr(args, "extra_nation_third_given_second_pct", 30.0), 0.30)
    _EXTRA_NATION_P4_GIVEN_P3 = _pct_to_prob(getattr(args, "extra_nation_fourth_given_third_pct", 33.333), (1.0/3.0))
    _EXTRA_NATION_P5PLUS_GIVEN_P4 = _pct_to_prob(getattr(args, "extra_nation_fifthplus_given_fourth_pct", 10.0), 0.10)
    _EXTRA_NATION_CHAIN_P = _pct_to_prob(getattr(args, "extra_nation_chain_pct", 20.0), 0.20)
    try:
        _EXTRA_NATION_MAX = int(getattr(args, "extra_nation_max", 8) or 8)
    except Exception:
        _EXTRA_NATION_MAX = 8
    if _EXTRA_NATION_MAX < 0:
        _EXTRA_NATION_MAX = 0
    if _EXTRA_NATION_MAX > 20:
        _EXTRA_NATION_MAX = 20
    
    _APPEARANCE_MODE = str(getattr(args, "appearance_mode", "nation") or "nation").strip().lower()
    if _APPEARANCE_MODE not in ("nation", "global"):
        _APPEARANCE_MODE = "nation"
    _GLOBAL_ETH_RANGE = _parse_range(getattr(args, "appearance_global_ethnicity", "0-10"), 0, 10)
    _GLOBAL_SKIN_RANGE = _parse_range(getattr(args, "appearance_global_skin", "0-19"), 0, 19)
    _GLOBAL_HAIR_RANGE = _parse_range(getattr(args, "appearance_global_hair_colour", "0-6"), 0, 6)
    _HAIR_LEN_WEIGHTS_MALE = _parse_w4(getattr(args, "hair_length_weights_male", "36,40,18,6"), (36,40,18,6))
    _HAIR_LEN_WEIGHTS_FEMALE = _parse_w4(getattr(args, "hair_length_weights_female", "8,20,34,38"), (8,20,34,38))
    w123, w4, w5 = _parse_w3(getattr(args, "body_type_weights", "95,4,1"), (95.0, 4.0, 1.0))
    _BODY_TYPE_W123, _BODY_TYPE_W4, _BODY_TYPE_W5 = w123, w4, w5
    
    try:
        _INTL_PLAY_PROB_MULT = float(getattr(args, "intl_play_prob_mult", 1.0) or 1.0)
    except Exception:
        _INTL_PLAY_PROB_MULT = 1.0
    if _INTL_PLAY_PROB_MULT < 0.0:
        _INTL_PLAY_PROB_MULT = 0.0
    if _INTL_PLAY_PROB_MULT > 5.0:
        _INTL_PLAY_PROB_MULT = 5.0
    
    _INTL_OPPONENT_MODE = str(getattr(args, "intl_opponent_mode", "random") or "random").strip().lower()
    if _INTL_OPPONENT_MODE not in ("random", "similar"):
        _INTL_OPPONENT_MODE = "random"
    
    try:
        _INTL_OPPONENT_SIMILARITY = float(getattr(args, "intl_opponent_similarity", 0.75) or 0.75)
    except Exception:
        _INTL_OPPONENT_SIMILARITY = 0.75
    if _INTL_OPPONENT_SIMILARITY < 0.0:
        _INTL_OPPONENT_SIMILARITY = 0.0
    if _INTL_OPPONENT_SIMILARITY > 1.0:
        _INTL_OPPONENT_SIMILARITY = 1.0
    
    # Toggle XML comments (default off)
    global _XML_COMMENTS
    try:
        _XML_COMMENTS = bool(getattr(args, "xml_comments", False))
    except Exception:
        _XML_COMMENTS = False
    # Compatibility aliases for GUI variants:
    # - some versions pass --second_name_text
    # - others pass --last_name_text
    # Prefer explicit --second_name_text if both are provided.
    resolved_last_name_text = (getattr(args, 'second_name_text', '') or '').strip() or (getattr(args, 'last_name_text', '') or '').strip()
    resolved_full_name_text = (getattr(args, 'full_name_text', '') or '').strip()
# --- parse editable position distributions (used only for RANDOM position profiles) ---
    def _parse_dist_list(s: str, expected: int) -> List[float]:
        parts = [p.strip() for p in (s or "").split(",") if p.strip() != ""]
        if len(parts) != expected:
            raise ValueError(f"Expected {expected} comma-separated values, got {len(parts)} in: {s!r}")
        out: List[float] = []
        for p in parts:
            out.append(float(p))
        return out
    
    try:
        pd = _parse_dist_list(args.pos_primary_dist, 4)
        nd = _parse_dist_list(args.pos_n20_dist, 9)
        # only accept if they roughly total 100; we'll normalize anyway
        if abs(sum(pd) - 100.0) > 0.001:
            print(f"[WARN] --pos_primary_dist totals {sum(pd):.3f} (expected 100). Normalizing.", file=sys.stderr)
        if abs(sum(nd) - 100.0) > 0.001:
            print(f"[WARN] --pos_n20_dist totals {sum(nd):.3f} (expected 100). Normalizing.", file=sys.stderr)
        # update extracted positions distributions
        _pos.PRIMARY_DIST = pd
        _pos.N20_DIST = nd
        PRIMARY_DIST = _pos.PRIMARY_DIST
        N20_DIST = _pos.N20_DIST
    except Exception as e:
        print(f"[FAIL] Invalid distribution arguments: {e}", file=sys.stderr)
        return 2
    
    # --- auto dev chance: accept 0-1 or 0-100 ---
    auto_dev_chance = float(args.auto_dev_chance)
    if auto_dev_chance > 1.0:
        auto_dev_chance = auto_dev_chance / 100.0
    auto_dev_chance = max(0.0, min(1.0, auto_dev_chance))
    common_name_chance = float(getattr(args, "common_name_chance", 5.0) or 0.0)
    if common_name_chance > 1.0:
        common_name_chance = common_name_chance / 100.0
    common_name_chance = max(0.0, min(1.0, common_name_chance))

    if args.pa_min > 200 or args.pa_max > 200:
        print("[FAIL] PA must be within 0..200 (you passed >200).", file=sys.stderr)
        return 2
    if args.ca_min > 200 or args.ca_max > 200:
        print("[FAIL] CA must be within 0..200.", file=sys.stderr)
        return 2

    fixed_dob = _parse_ymd(args.dob) if args.dob else None
    dob_start = _parse_ymd(args.dob_start) if args.dob_start else None
    dob_end = _parse_ymd(args.dob_end) if args.dob_end else None
    moved_to_nation_date = _parse_ymd(args.moved_to_nation_date) if args.moved_to_nation_date else None
    joined_club_date = _parse_ymd(args.joined_club_date) if args.joined_club_date else None
    contract_expires_date = _parse_ymd(args.contract_expires_date) if args.contract_expires_date else None
    date_last_signed = _parse_ymd(args.date_last_signed) if args.date_last_signed else None
    if (date_last_signed is None) and getattr(args, "last_contract_signed_date", ""):
        date_last_signed = _parse_ymd(args.last_contract_signed_date)
    international_retirement_date = _parse_ymd(args.international_retirement_date) if args.international_retirement_date else None
    international_debut_date = None if (str(args.international_debut_date).strip() in ('', '__NONE__')) else _parse_ymd(args.international_debut_date)
    u21_international_debut_date = None if (str(args.u21_international_debut_date).strip() in ('', '__NONE__')) else _parse_ymd(args.u21_international_debut_date)
    first_international_goal_date = None if (str(getattr(args, 'first_international_goal_date', '')).strip() in ('', '__NONE__')) else _parse_ymd(getattr(args, 'first_international_goal_date'))
    if str(getattr(args, 'other_nation_caps_json', '') or '').strip():
        print("[WARN] --other_nation_caps_json accepted for GUI compatibility but not yet written to XML in this build.", file=sys.stderr)
    if str(getattr(args, 'other_nation_youth_caps_json', '') or '').strip():
        print("[WARN] --other_nation_youth_caps_json accepted for GUI compatibility but not yet written to XML in this build.", file=sys.stderr)

    fixed_height = args.height if args.height else None
    height_min = int(args.height_min)
    height_max = int(args.height_max)

    fixed_club = (args.club_dbid, args.club_large) if (args.club_dbid and args.club_large) else None
    fixed_city = (args.city_dbid, args.city_large) if (args.city_dbid and args.city_large) else None
    fixed_nation = (args.nation_dbid, args.nation_large) if (args.nation_dbid and args.nation_large) else None

    fixed_left_foot = args.left_foot if args.left_foot else None
    fixed_right_foot = args.right_foot if args.right_foot else None
    feet_mode = args.feet

    nationality_info_value_resolved = None
    if _nat_info_explicit:
        try:
            nationality_info_value_resolved = resolve_nationality_info(args.nationality_info_value, getattr(args, 'nationality_info', ''))
        except Exception as e:
            print(f"[FAIL] {e}", file=sys.stderr)
            return 2

    # legacy positions
    fixed_positions = None
    if args.positions:
        pos = [p.strip().upper() for p in args.positions.split(",") if p.strip()]
        if len(pos) == 1 and pos[0] == "RANDOM":
            fixed_positions = []
        else:
            for p in pos:
                if p not in POS_PROPS:
                    print(f"[FAIL] Unknown position: {p}. Allowed: {', '.join(ALL_POS)} or RANDOM", file=sys.stderr)
                    return 2
            fixed_positions = pos

    # new positions
    pos_primary = args.pos_primary.strip().upper() if args.pos_primary.strip() else None

    pos_20 = [p.strip().upper() for p in args.pos_20.split(",") if p.strip()] if args.pos_20.strip() else None
    pos_dev = [p.strip().upper() for p in args.pos_dev.split(",") if p.strip()] if args.pos_dev.strip() else None

    args.output = _resolve_output_xml_path(args.output)

    # --- injected: sync settings-pack globals back into generator module for generate_players_xml() ---
    if g is not None:
        _sync_names = [
            "_NAME_LOCAL_BIAS", "_FEMALE_PCT",
            "_EXTRA_NATION_P2", "_EXTRA_NATION_P3_GIVEN_P2", "_EXTRA_NATION_P4_GIVEN_P3",
            "_EXTRA_NATION_P5PLUS_GIVEN_P4", "_EXTRA_NATION_CHAIN_P", "_EXTRA_NATION_MAX",
            "_APPEARANCE_MODE", "_GLOBAL_ETH_RANGE", "_GLOBAL_SKIN_RANGE", "_GLOBAL_HAIR_RANGE",
            "_HAIR_LEN_WEIGHTS_MALE", "_HAIR_LEN_WEIGHTS_FEMALE", "_BODY_TYPE_W123", "_BODY_TYPE_W4", "_BODY_TYPE_W5",
            "_INTL_PLAY_PROB_MULT", "_INTL_OPPONENT_MODE", "_INTL_OPPONENT_SIMILARITY",
            "_XML_COMMENTS",
            "PRIMARY_DIST", "N20_DIST",
        ]
        _loc = locals()
        for _k in _sync_names:
            if _k in _loc:
                try:
                    setattr(g, _k, _loc[_k])
                except Exception:
                    pass
    # --- end injected sync ---

    try:
        generate_players_xml(
            library_csv=args.library_csv,
            out_xml=args.output,
            count=args.count,
            seed=args.seed,
            append=args.append,
            start_index=args.start_index,
            age_min=args.age_min,
            age_max=args.age_max,
            ca_min=args.ca_min,
            ca_max=args.ca_max,
            pa_min=args.pa_min,
            pa_max=args.pa_max,
            base_year=args.base_year,
            version=args.version,
            first_names_csv=args.first_names,
            female_first_names_csv=(args.female_first_names or None),
            common_names_csv=(args.common_names or None),
            common_name_chance=common_name_chance,
            surnames_csv=args.surnames,
            fixed_first_name=(args.first_name_text or None),
            fixed_second_name=(resolved_last_name_text or None),
            fixed_common_name=(args.common_name_text or None),
            fixed_full_name=(resolved_full_name_text or None),
            person_type_value=args.person_type_value,
            gender_value=args.gender_value,
            ethnicity_value=args.ethnicity_value,
            hair_colour_value=args.hair_colour_value,
            hair_length_value=args.hair_length_value,
            skin_tone_value=args.skin_tone_value,
            body_type_value=args.body_type_value,
            fixed_dob=fixed_dob,
            dob_start=dob_start,
            dob_end=dob_end,
            moved_to_nation_date=moved_to_nation_date,
            joined_club_date=joined_club_date,
            contract_expires_date=contract_expires_date,
            date_last_signed=date_last_signed,
            squad_status=args.squad_status,
            fixed_height=fixed_height,
            height_min=height_min,
            height_max=height_max,
            fixed_club=fixed_club,
            club_assign_pct=args.club_assign_pct,
            fixed_city=fixed_city,
            fixed_nation=fixed_nation,
            fixed_positions=fixed_positions,
            pos_primary=pos_primary,
            pos_20=pos_20,
            pos_all_outfield_20=bool(args.pos_all_outfield_20),
            pos_dev=pos_dev,
            pos_dev_mode=args.pos_dev_mode,
            pos_dev_value=args.pos_dev_value,
            pos_dev_min=args.pos_dev_min,
            pos_dev_max=args.pos_dev_max,
            feet_mode=feet_mode,
            fixed_left_foot=fixed_left_foot,
            fixed_right_foot=fixed_right_foot,
            wage=args.wage,
            wage_min=args.wage_min,
            wage_max=args.wage_max,
            rep_current=args.rep_current,
            rep_home=args.rep_home,
            rep_world=args.rep_world,
            rep_min=args.rep_min,
            rep_max=args.rep_max,
            transfer_mode=args.transfer_mode,
            transfer_value=args.transfer_value,
            transfer_min=args.transfer_min,
            transfer_max=args.transfer_max,
            international_apps=args.international_apps,
            international_goals=args.international_goals,
            u21_international_apps=args.u21_international_apps,
            u21_international_goals=args.u21_international_goals,
            international_debut_date=international_debut_date,
            international_debut_against_name=(args.international_debut_against or None),
            u21_international_debut_date=u21_international_debut_date,
            u21_international_debut_against_name=(args.u21_international_debut_against or None),
            first_international_goal_date=first_international_goal_date,
            first_international_goal_against_name=(getattr(args, "first_international_goal_against", "") or None),
            nationality_info_value=nationality_info_value_resolved,
            second_nation_specs=list(getattr(args, "second_nation", []) or []),
            international_retirement=bool(args.international_retirement),
            international_retirement_date=international_retirement_date,
            retiring_after_spell_current_club=bool(args.retiring_after_spell_current_club),
            id_registry_path=args.id_registry_path,
            id_registry_mode=args.id_registry_mode,
            id_namespace_salt=args.id_namespace_salt,
            omit_fields=args.omit_field,
        )
    except Exception as e:
        print(f"[FAIL] {e}", file=sys.stderr)
        return 1

    print(f"[OK] Wrote: {args.output} (count={args.count}, append={args.append})")
    return 0


