# -*- coding: utf-8 -*-
from __future__ import annotations

# Settings pack defaults (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_fm_props_and_config_v1.py

from typing import Tuple

_NAME_LOCAL_BIAS = 0.85

_FEMALE_PCT = 50.0

_APPEARANCE_MODE = "nation"  # nation|global

_GLOBAL_ETH_RANGE = (0, 10)

_GLOBAL_SKIN_RANGE = (0, 19)

_GLOBAL_HAIR_RANGE = (0, 6)

_HAIR_LEN_WEIGHTS_MALE = (36, 40, 18, 6)

_HAIR_LEN_WEIGHTS_FEMALE = (8, 20, 34, 38)

_BODY_TYPE_W123 = 95.0

_BODY_TYPE_W4 = 4.0

_BODY_TYPE_W5 = 1.0



def configure_from_globals(g: dict) -> None:
    """Copy known config vars from generator globals into this module."""
    for k in (
        '_NAME_LOCAL_BIAS',
        '_FEMALE_PCT',
        '_APPEARANCE_MODE',
        '_GLOBAL_ETH_RANGE',
        '_GLOBAL_SKIN_RANGE',
        '_GLOBAL_HAIR_RANGE',
        '_HAIR_LEN_WEIGHTS_MALE',
        '_HAIR_LEN_WEIGHTS_FEMALE',
        '_BODY_TYPE_W123',
        '_BODY_TYPE_W4',
        '_BODY_TYPE_W5',
    ):
        if k in g:
            globals()[k] = g[k]


__all__ = [k for k in globals().keys() if not k.startswith('__')]
