# -*- coding: utf-8 -*-
from __future__ import annotations

# Emit blocks (extracted from generator)
# Auto-generated by fm26_patch_peoplegen_extract_emit_identity_positions_block_v1.py

from typing import Any, Dict, Optional

# Bind XML helpers used by the block
from peoplegen import xml_writer as _xmlw
_int = _xmlw._int
_uns = _xmlw._uns
_large = _xmlw._large
_str = _xmlw._str
_bool = _xmlw._bool
_rec = _xmlw._rec
_attr = _xmlw._attr

# Import FM props/constants and positions
from peoplegen.fm_props import *  # noqa
from peoplegen.positions import POS_PROPS

def emit_identity_appearance_positions(*,
    push,
    rid,
    _is_omitted,
    person_uid: int,
    version: int,
    fn: str,
    sn: str,
    cn: str,
    fixed_full_name,
    person_type_value,
    eff_gender_value: int,
    eff_ethnicity_value: int,
    eff_hair_colour_value: int,
    eff_hair_length_value: int,
    eff_skin_tone_value: int,
    eff_body_type_value: int,
    lang_extra: str,
    odvl0: str,
    pos_map: dict,
):
    """Emit identity/appearance/positions records for one player."""
    # string fields (with language flag)
    emit.push_attr(person_uid, PROP_FIRST_NAME, _str("new_value", fn), "rid|fn", version, "First Name", "first_name", "first_name_text", extra=lang_extra)
    emit.push_attr(person_uid, PROP_SECOND_NAME, _str("new_value", sn), "rid|sn", version, "Second Name", "second_name", "second_name_text", extra=lang_extra)
    emit.push_attr(person_uid, PROP_COMMON_NAME, _str("new_value", cn), "rid|cn", version, "Common Name", "common_name", "common_name_text", extra=lang_extra)
    full_name = (fixed_full_name.strip() if isinstance(fixed_full_name, str) and fixed_full_name.strip() else f"{fn} {sn}".strip())
    emit.push_attr(person_uid, PROP_FULL_NAME, _str("new_value", full_name), "rid|full_name", version, "Full Name", "full_name", "full_name_text", odvl=_str("odvl", f"{fn} {sn}".strip()))
    if person_type_value is not None:
        _pt = int(person_type_value)
        _pt_odvl = 1 if _pt == 2 else 2
        emit.push_attr(person_uid, PROP_PERSON_TYPE, _int("new_value", _pt), "rid|ptype", version, "Person Type", "person_type", "person_type_value", odvl=_int("odvl", _pt_odvl))
    # FM gender mapping: FM expects 0=male, 1=female (match GUI/internal)
    fm_gender_value = 1 if (int(eff_gender_value) == 1) else 0
    emit.push_attr(person_uid, PROP_GENDER, _int("new_value", fm_gender_value), "rid|gender", version, "Gender", "gender", "gender_value", odvl=_bool("odvl", False))
    emit.push_attr(person_uid, PROP_ETHNICITY, _int("new_value", eff_ethnicity_value), "rid|ethnicity", version, "Ethnicity", "ethnicity", "ethnicity_value", odvl=_int("odvl", -1))
    emit.push_attr(person_uid, PROP_HAIR_COLOUR, _int("new_value", eff_hair_colour_value), "rid|hair_colour", version, "Hair Colour", "hair_colour", "hair_colour_value", odvl=_uns("odvl", 3))
    emit.push_attr(person_uid, PROP_HAIR_LENGTH, _int("new_value", eff_hair_length_value), "rid|hair_length", version, "Hair Length", "hair_length", "hair_length_value", odvl=_uns("odvl", 1))
    emit.push_attr(person_uid, PROP_SKIN_TONE, _int("new_value", eff_skin_tone_value), "rid|skin_tone", version, "Skin Tone", "skin_tone", "skin_tone_value", odvl=_int("odvl", -1))
    emit.push_attr(person_uid, PROP_BODY_TYPE, _int("new_value", eff_body_type_value), "rid|body_type", version, "Body Type", "body_type", "body_type_value", odvl=_uns("odvl", 3))
    # scalar ints/dates
    emit.push_attr(person_uid, PROP_HEIGHT, _int("new_value", int(height)), "rid|h", version, "Height", "height", "height_min", "height_max", odvl=odvl0)
    emit.push_attr(person_uid, PROP_DOB, _date("new_value", dob), "rid|dob", version, "DOB", "dob", "dob_start", "dob_end", odvl=odvl_date)
    # [PATCH RESTORE PLAYER FIELDS v1]
    # Ability (CA/PA)
    emit.push_attr(person_uid, PROP_CA, _int("new_value", int(ca)), "rid|ca", version, "Current Ability", "ca", odvl=odvl0)
    emit.push_attr(person_uid, PROP_PA, _int("new_value", int(pa)), "rid|pa", version, "Potential Ability", "pa", odvl=odvl0)
    # Feet (1..20)
    emit.push_attr(person_uid, PROP_LEFT_FOOT, _int("new_value", int(left)), "rid|left_foot", version, "Left Foot", "feet", odvl=odvl0)
    emit.push_attr(person_uid, PROP_RIGHT_FOOT, _int("new_value", int(right)), "rid|right_foot", version, "Right Foot", "feet", odvl=odvl0)
    # Wage / Reputation / Transfer
    if club_record_emit:
        emit.push_attr(person_uid, PROP_WAGE, _int("new_value", int(wage_val)), "rid|wage", version, "Wage", "wage", odvl=odvl0)
        emit.push_attr(person_uid, PROP_TRANSFER_VALUE, _int("new_value", int(tv)), "rid|transfer_value", version, "Transfer Value", "transfer_value", odvl=odvl0)
    emit.push_attr(person_uid, PROP_CURRENT_REP, _int("new_value", int(rep_cur)), "rid|rep_current", version, "Current Reputation", "rep_current", odvl=odvl0)
    emit.push_attr(person_uid, PROP_HOME_REP, _int("new_value", int(rep_home_v)), "rid|rep_home", version, "Home Reputation", "rep_home", odvl=odvl0)
    emit.push_attr(person_uid, PROP_WORLD_REP, _int("new_value", int(rep_world_v)), "rid|rep_world", version, "World Reputation", "rep_world", odvl=odvl0)
    # Contract / squad (dates)
    emit.push_attr(person_uid, PROP_DATE_MOVED_TO_NATION, _date("new_value", moved_to_nation), "rid|moved_to_nation", version, "Date moved to nation", "moved_to_nation_date", odvl=odvl_date)
    if club_record_emit:
        emit.push_attr(person_uid, PROP_DATE_JOINED_CLUB, _date("new_value", joined), "rid|date_joined_club", version, "Date joined club", "joined_club_date", odvl=odvl_date)
        emit.push_attr(person_uid, PROP_DATE_LAST_SIGNED, _date("new_value", last_signed), "rid|date_last_signed", version, "Date last signed", "date_last_signed", odvl=odvl_date)
        emit.push_attr(person_uid, PROP_CONTRACT_EXPIRES, _date("new_value", expires), "rid|contract_expires", version, "Contract expires", "contract_expires_date", odvl=odvl_date)
        emit.push_attr(person_uid, PROP_SQUAD_STATUS, _int("new_value", int(squad_status_val)), "rid|squad_status", version, "Squad status", "squad_status", odvl=odvl0)
    # Positions (write all position props unless omitted)
    if not _is_omitted("positions"):
        for _p, _pid in POS_PROPS.items():
            _v = int(pos_map.get(_p, 1))
            push(_rec(_attr(person_uid, int(_pid), _int("new_value", _v), rid(f"rid|pos|{_p}"), version, odvl=odvl0), f"Position {_p}"), "positions")




def emit_city_nation_club(*, ctx: dict) -> None:
    """Emit city/nation/second-nations/international/club block (moved verbatim)."""
    old = _ctx_apply(ctx)
    try:
        # city record
                newv = (
                    '<record id="new_value">\n'
                    + f'\t\t\t\t{_large("city", city_large)}\n'
                    + f'\t\t\t\t{_int("DBID", city_dbid)}\n'
                    + "\t\t\t</record>"
                )
                emit.push_attr(person_uid, CITY_PROPERTY, newv, "rid|city", version, "City of birth", "city", "city_dbid", "city_large", "city_of_birth", odvl=_null("odvl"))
                # nation record (+ odvl record)
                newv = (
                    '<record id="new_value">\n'
                    + f'\t\t\t\t{_large("Nnat", nation_large)}\n'
                    + f'\t\t\t\t{_int("DBID", nation_dbid)}\n'
                    + "\t\t\t</record>"
                )
                odvl = '<record id="odvl">\n' + f'\t\t\t\t{_large("Nnat", DEFAULT_NNAT_ODVL)}\n' + "\t\t\t</record>"
                emit.push_attr(person_uid, NATION_PROPERTY, newv, "rid|nation", version, "Nation", "nation", "nation_dbid", "nation_large", odvl=odvl)
                # second nations list entries (FM property 1347310195)
                _effective_second_nations = list(parsed_second_nations or [])
                if not _effective_second_nations:
                    _effective_second_nations.extend(_build_random_extra_second_nations(
                        rng,
                        nations,
                        (int(nation_dbid), int(nation_large)),
                        existing_rows=parsed_second_nations,
                    ))

                if _effective_second_nations and not _is_omitted("second_nation","second_nations","second_nation_specs"):
                    for _sn in _effective_second_nations:
                        push(_rec(_attr_second_nations_listop(person_uid, rid("rid|second_nation|prep"), version, lsop=0), "Second nation list prep"), "second_nation", "second_nations", "second_nation_specs")
                    for _sn_idx, _sn in enumerate(_effective_second_nations, start=2):
                        _comment = "Second nation" if _sn_idx == 2 else f"{_sn_idx}th nation"
                        if _sn_idx == 3:
                            _comment = "Third nation"
                        _sn_large = int(_sn["large"])
                        _sn_ntin = int(_sn.get("ntin", 80))
                        frags.append(_rec(_attr_second_nations_listop(
                            person_uid,
                            rid(f"rid|second_nation|{_sn_idx}"),
                            version,
                            lsop=1,
                            dbid=int(_sn["dbid"]),
                            large=_sn_large,
                            ntin=_sn_ntin,
                        ), _comment))
                        frags.append(_rec(_attr_second_nation_nationality_info(
                            person_uid,
                            rid(f"rid|second_nation_natinf|{_sn_idx}"),
                            version,
                            nation_large=_sn_large,
                            ntin_value=_sn_ntin,
                        ), f"{_comment} nationality info"))

                # nationality info (default bias = ~95% Born In Nation unless explicitly overridden)
                _effective_primary_natinf = int(nationality_info_value) if nationality_info_value is not None else _pick_primary_nationality_info_default(rng)
                emit.push_attr(person_uid, PROP_NATIONALITY_INFO, _int("new_value", int(_effective_primary_natinf)), "rid|ninfo", version, "Nationality Info", "nationality_info", "nationality_info_value", "nationality_info", "nationality_info_value", odvl=odvl0)
                if declared_for_youth_nation is not None and not _is_omitted("declared_for_youth_nation","declared_for_youth_nation_name"):
                    _dy_dbid, _dy_large = declared_for_youth_nation
                    _dy_newv = (
                        '<record id="new_value">\n'
                        + f'\t\t\t\t{_large("Nnat", int(_dy_large))}\n'
                        + f'\t\t\t\t{_int("DBID", int(_dy_dbid))}\n'
                        + "\t\t\t</record>"
                    )
                    emit.push_attr(person_uid, PROP_DECLARED_FOR_YOUTH_NATION, _dy_newv, "rid|declared_for_youth_nation", version, "Declared For Nation At Youth Level", "declared_for_youth_nation", odvl=_null("odvl"))
                _intl_apps_eff = international_apps
                _intl_goals_eff = international_goals
                _u21_apps_eff = u21_international_apps
                _u21_goals_eff = u21_international_goals
                _intl_debut_date_eff = international_debut_date
                _intl_debut_against_eff = international_debut_against
                _first_goal_date_eff_player = _first_goal_date_eff
                _first_goal_against_eff_player = first_international_goal_against

                _need_auto_intl = any(v is _AUTO_INTL for v in (_intl_apps_eff, _intl_goals_eff, _u21_apps_eff, _u21_goals_eff))
                if _need_auto_intl:
                    _sen_caps_auto, _sen_goals_auto = _estimate_international_stats(rng, age=age, ca=ca, pa=pa, nation_name=primary_nation_name, max_caps=250, max_goals=250, youth=False)
                    _u21_caps_auto, _u21_goals_auto = _estimate_international_stats(rng, age=age, ca=ca, pa=pa, nation_name=primary_nation_name, max_caps=100, max_goals=100, youth=True)

                    if _intl_apps_eff is _AUTO_INTL: _intl_apps_eff = _sen_caps_auto
                    if _u21_apps_eff is _AUTO_INTL: _u21_apps_eff = _u21_caps_auto

                    # Goals: scale with caps + position group + PA (more realistic than a flat goal rate)
                    _pa_fac = max(0.0, min(1.0, (pa - 70) / 120.0))
                    _sf_loc = float(_intl_strength_factor(primary_nation_name))
                    _gk = int(pos_map.get("GK", 1))
                    _att = max(int(pos_map.get("ST", 1)), int(pos_map.get("AMC", 1)), int(pos_map.get("AML", 1)), int(pos_map.get("AMR", 1)))
                    _def = max(int(pos_map.get("DC", 1)), int(pos_map.get("DL", 1)), int(pos_map.get("DR", 1)), int(pos_map.get("WBL", 1)), int(pos_map.get("WBR", 1)))
                    if _gk >= 15:
                        _role = "gk"
                    elif _att >= 15:
                        _role = "att"
                    elif _def >= 15:
                        _role = "def"
                    else:
                        _role = "mid"

                    def _pick_rate(_role_name: str, youth: bool) -> float:
                        if _role_name == "gk":
                            lo, hi = (0.0, 0.02)
                        elif _role_name == "def":
                            lo, hi = (0.04, 0.18)
                        elif _role_name == "mid":
                            lo, hi = (0.12, 0.38)
                        else:
                            lo, hi = (0.30, 0.75)
                        if youth:
                            lo *= 0.75
                            hi *= 0.75
                        mult = (0.85 + 0.35 * _pa_fac) * (0.90 + 0.20 * _sf_loc)
                        lo *= mult
                        hi *= mult
                        return rng.uniform(lo, hi)

                    if _intl_goals_eff is _AUTO_INTL:
                        _cap = int(_intl_apps_eff or 0)
                        _rate = _pick_rate(_role, False)
                        _g = int(round(_cap * _rate))
                        _intl_goals_eff = max(0, min(_cap, _g, 250))

                    if _u21_goals_eff is _AUTO_INTL:
                        _cap = int(_u21_apps_eff or 0)
                        _rate = _pick_rate(_role, True)
                        _g = int(round(_cap * _rate))
                        _u21_goals_eff = max(0, min(_cap, _g, 100))

                    _today_est = dt.date(base_year, 6, 30)
                    # Realistic debut window: scale debut date with caps and nation match frequency
                    _sf_py = float(_intl_strength_factor(primary_nation_name))
                    _matches_py = int(max(5, min(12, round(5 + 7 * _sf_py))))
                    if _intl_apps_eff and int(_intl_apps_eff) > 0 and _intl_debut_date_eff is None:
                        _caps = int(_intl_apps_eff)
                        _years_needed = max(0.0, float(_caps) / float(_matches_py))
                        _ideal_start = _today_est - dt.timedelta(days=int(_years_needed * 365.25))
                        _min_start = max(dob + dt.timedelta(days=16*365), dt.date(dob.year + 16, 1, 1))
                        _start = max(_min_start, _ideal_start - dt.timedelta(days=rng.randint(0, 180)))
                        _end = min(_today_est, _start + dt.timedelta(days=365))
                        if _end < _start:
                            _end = _today_est
                        if _end >= _start:
                            _intl_debut_date_eff = _random_date_between(rng, _start, _end)
                    if _intl_apps_eff and _intl_apps_eff > 0 and _intl_debut_against_eff is None:
                        _intl_debut_against_eff = _maybe_pick_random_opponent_nation(rng, nation_lookup, exclude_names=[primary_nation_name], own_nation_name=primary_nation_name)
                    if _intl_goals_eff and _intl_goals_eff > 0 and _first_goal_date_eff_player is None:
                        _fg_start = _intl_debut_date_eff or max(dob + dt.timedelta(days=16*365), dt.date(max(base_year-35, dob.year+16), 1, 1))
                        _fg_end = _today_est
                        if _fg_end >= _fg_start:
                            _first_goal_date_eff_player = _random_date_between(rng, _fg_start, _fg_end)
                    if _intl_goals_eff and _intl_goals_eff > 0 and _first_goal_against_eff_player is None:
                        _first_goal_against_eff_player = _maybe_pick_random_opponent_nation(rng, nation_lookup, exclude_names=[primary_nation_name], own_nation_name=primary_nation_name)

                # international data (optional test fields from International Data tab)
                if (not _is_omitted('international_apps')) and _intl_apps_eff is not None:
                    emit.push_attr(person_uid, PROP_INTERNATIONAL_APPS, _int("new_value", int(_intl_apps_eff)), "rid|international_apps", version, "International appearances", "international_apps", odvl=odvl0)
                if (not _is_omitted('international_goals')) and _intl_goals_eff is not None:
                    emit.push_attr(person_uid, PROP_INTERNATIONAL_GOALS, _int("new_value", int(_intl_goals_eff)), "rid|international_goals", version, "International goals", "international_goals", odvl=odvl0)
                if (not _is_omitted('u21_international_apps','under_21_international_apps')) and _u21_apps_eff is not None:
                    emit.push_attr(person_uid, PROP_U21_INTERNATIONAL_APPS, _int("new_value", int(_u21_apps_eff)), "rid|u21_international_apps", version, "U21 International appearances", "u21_international_apps", odvl=odvl0)
                if (not _is_omitted('u21_international_goals','under_21_international_goals')) and _u21_goals_eff is not None:
                    emit.push_attr(person_uid, PROP_U21_INTERNATIONAL_GOALS, _int("new_value", int(_u21_goals_eff)), "rid|u21_international_goals", version, "U21 International goals", "u21_international_goals", odvl=odvl0)
                if (not _is_omitted('international_debut_date')) and _intl_debut_date_eff is not None:
                    emit.push_attr(person_uid, PROP_INTERNATIONAL_DEBUT_DATE, _date("new_value", _intl_debut_date_eff), "rid|international_debut_date", version, "International debut date", "international_debut_date", odvl=odvl_date)
                if (not _is_omitted('international_debut_against')) and _intl_debut_against_eff is not None:
                    _ida_dbid, _ida_large = _intl_debut_against_eff
                    _ida_newv = (
                        "<record id=\"new_value\">\n"
                        + f'\t\t\t\t{_large("Nnat", int(_ida_large))}\n'
                        + f'\t\t\t\t{_int("DBID", int(_ida_dbid))}\n'
                        + "\t\t\t</record>"
                    )
                    emit.push_attr(person_uid, PROP_INTERNATIONAL_DEBUT_AGAINST, _ida_newv, "rid|international_debut_against", version, "International debut against", "international_debut_against", "international_debut_against_name", odvl=_null("odvl"))
                if u21_international_debut_date is not None:
                    emit.push_attr(person_uid, PROP_U21_INTERNATIONAL_DEBUT_DATE, _date("new_value", u21_international_debut_date), "rid|u21_international_debut_date", version, "U21 International debut date", "u21_international_debut_date", odvl=odvl_date)
                if u21_international_debut_against is not None:
                    _u21da_dbid, _u21da_large = u21_international_debut_against
                    _u21da_newv = (
                        "<record id=\"new_value\">\n"
                        + f'\t\t\t\t{_large("Nnat", int(_u21da_large))}\n'
                        + f'\t\t\t\t{_int("DBID", int(_u21da_dbid))}\n'
                        + "\t\t\t</record>"
                    )
                    emit.push_attr(person_uid, PROP_U21_INTERNATIONAL_DEBUT_AGAINST, _u21da_newv, "rid|u21_international_debut_against", version, "U21 International debut against", "u21_international_debut_against", "u21_international_debut_against_name", odvl=_null("odvl"))
                # optional international retirement / nationality metadata
                if bool(international_retirement) and not _is_omitted("international_retirement"):
                    emit.push_attr(person_uid, PROP_INTERNATIONAL_RETIREMENT, _bool("new_value", True), "rid|intl_ret", version, "International Retirement", "international_retirement", odvl=_bool("odvl", False))
                if international_retirement_date is not None and not _is_omitted("international_retirement_date"):
                    emit.push_attr(person_uid, PROP_INTERNATIONAL_RETIREMENT_DATE, _date("new_value", international_retirement_date), "rid|intl_ret_date", version, "International Retirement Date", "international_retirement", odvl=odvl_date)
                if bool(retiring_after_spell_current_club) and not _is_omitted("retiring_after_spell_current_club"):
                    emit.push_attr(person_uid, PROP_RETIRING_AFTER_SPELL_CURRENT_CLUB, _bool("new_value", True), "rid|intl_ret_end_season", version, "International Retirement end of club season", "retiring_after_spell_current_club", odvl=_bool("odvl", False))
                # club record (clean v16)

                # - if club is omitted => no record emitted (free agent)

                # - otherwise emit club record only club_assign_pct% of the time (computed once as club_record_emit)

                if club_record_emit:

                    newv = (

                        '<record id="new_value">\n'

                        + f'\t\t\t\t{_large("Ttea", club_large)}\n'

                        + f'\t\t\t\t{_int("DBID", club_dbid)}\n'

                        + "\t\t\t</record>"

                    )

                    emit.push_attr(person_uid, CLUB_PROPERTY, newv, "rid|club", version, "Club", "club", "club_dbid", "club_large", odvl=_null("odvl"))
    finally:
        _ctx_restore(old)


__all__ = [k for k in globals().keys() if not k.startswith('__')]
