# -*- coding: utf-8 -*-
from __future__ import annotations

# International stats helpers (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_international_v2.py

import random
import datetime as _dt
from typing import Dict, List, Tuple, Optional

def configure_from_globals(g: dict) -> None:
    ""Best-effort sync of config globals from fm26_people_generator.py.""
    for k, v in list(g.items()):
        try:
            ks = str(k)
        except Exception:
            continue
        if ks.startswith('INTL_') or ks.startswith('_INTL_') or ('international' in ks.lower()):
            globals()[ks] = v

# -------------------------------------------------------------------

PROP_INTERNATIONAL_RETIREMENT = 1349675364

PROP_INTERNATIONAL_RETIREMENT_DATE = 1349087844

PROP_INTERNATIONAL_APPS = 1349083504

PROP_INTERNATIONAL_GOALS = 1349085036

PROP_U21_INTERNATIONAL_APPS = 1349871969

PROP_U21_INTERNATIONAL_GOALS = 1349871975

PROP_INTERNATIONAL_DEBUT_DATE = 1349084260

PROP_INTERNATIONAL_DEBUT_AGAINST = 1346978927

PROP_U21_INTERNATIONAL_DEBUT_DATE = 1349085028

PROP_U21_INTERNATIONAL_DEBUT_AGAINST = 1346979695

_INTL_PLAY_PROB_MULT = 1.0

_INTL_OPPONENT_MODE = "random"  # random|similar

_INTL_OPPONENT_SIMILARITY = 0.75

def _intl_strength_factor(nation_name: Optional[str]) -> float:
    n = (nation_name or "").strip().lower()
    if not n:
        return 0.50
    strong = {"argentina","brazil","england","france","germany","spain","italy","portugal","netherlands","belgium","croatia","uruguay","colombia","denmark"}
    mid = {"scotland","wales","ireland","northern ireland","norway","sweden","switzerland","austria","poland","serbia","turkiye","turkey","czech republic","czechia","ukraine","morocco","senegal","japan","south korea","mexico","usa","united states"}
    low = {"andorra","san marino","gibraltar","faroe islands","malta","liechtenstein","luxembourg"}
    if n in strong: return 0.95
    if n in mid: return 0.65
    if n in low: return 0.25
    return 0.50

def _estimate_international_stats(rng: random.Random, *, age: int, ca: int | None = None, pa: int = 100, nation_name: Optional[str], max_caps: int, max_goals: int, youth: bool = False) -> Tuple[int, int]:
    # Auto-generate international caps/goals.
    #
    # Key goals:
    # - Elite nations should VERY rarely give caps to low-CA teenagers.
    # - Minor nations can hand out caps earlier (still bounded/sensible).
    # - Uses CA heavily for elite nations; PA has a smaller influence (future upside).
    #
    age = max(14, min(50, int(age)))
    pa = max(1, min(200, int(pa)))
    if ca is None:
        ca = pa
    ca = max(1, min(200, int(ca)))

    strength = float(_intl_strength_factor(nation_name))  # 0..1 (higher = stronger nation)
    pa_factor = max(0.0, min(1.0, (pa - 70) / 120.0))
    ca_factor = max(0.0, min(1.0, (ca - 60) / 120.0))

    # Ability mix: elite nations care more about CA (current ability).
    # Minor nations lean slightly more towards PA (potential).
    w_ca = 0.80 * strength + 0.45 * (1.0 - strength)   # 0.80..0.45
    w_pa = 1.0 - w_ca
    ability = (w_ca * ca_factor) + (w_pa * pa_factor)

    # CA "gate": required CA rises sharply for strong nations and for younger ages.
    if youth:
        # Youth caps can exist from 14+, but elite nations require a very strong teenager.
        required_ca = 65.0 + (50.0 * strength) + (max(0, 18 - age) * 5.0)
    else:
        # Senior caps: for age 15-16, elite nations require near-elite CA.
        required_ca = 75.0 + (55.0 * strength) + (max(0, 22 - age) * 6.0)

    # Gate multiplier goes to ~0 when ca << required_ca, and ~1 when ca >= required_ca.
    ratio = max(0.0, min(1.5, ca / max(1.0, required_ca)))
    gate = min(1.0, ratio ** 6)  # steep curve

    # Career length proxy (still conservative for teens)
    if youth:
        years = max(0.0, min(7.0, age - 13.0))  # 14->1, 16->3, 20->7
        games_per_year = 1.2 + (3.2 * (1.0 - strength)) + (2.8 * ability)
        cap_ceiling = int(min(max_caps, max(0, round(years * games_per_year))))
        base_prob = 0.02 + (0.55 * ability) + (0.15 * (1.0 - strength)) + (0.02 * min(years, 6.0))
    else:
        if age == 14:
            return (0, 0)
        years = 0.25 if age == 15 else (0.75 if age == 16 else max(0.0, float(age) - 16.0))
        games_per_year = 0.8 + (3.8 * (1.0 - strength)) + (3.5 * ability)
        cap_ceiling = int(min(max_caps, max(0, round(years * games_per_year))))
        age_maturity = max(0.0, min(1.0, (age - 18) / 12.0))
        base_prob = 0.008 + (0.50 * ability) + (0.10 * (1.0 - strength)) + (0.18 * age_maturity) + (0.02 * min(years, 8.0))

    # Apply global multiplier if present
    try:
        base_prob = float(base_prob) * float(_INTL_PLAY_PROB_MULT)
    except Exception:
        pass

    play_prob = max(0.0, min(0.995, float(base_prob) * float(gate)))

    if cap_ceiling <= 0 or rng.random() > play_prob:
        return (0, 0)

    # For elite nations, also cap the ceiling harder for low ability
    # (prevents 5+ caps for mediocre teens in Brazil/Argentina).
    elite_hard_cap = int(max(1, round(cap_ceiling * (0.35 + 0.65 * ability) * (0.55 + 0.45 * gate))))
    cap_ceiling = max(1, min(cap_ceiling, elite_hard_cap))

    # Bias caps toward smaller values unless truly strong.
    bias = 0.18 + 0.55 * ability
    caps = _weighted_randint(rng, 1, cap_ceiling, bias=bias)

    # Goals here are not heavily relied on (generator also derives goals from caps + role),
    # but keep them bounded and conservative.
    goal_rate = (0.01 + 0.06 * ability + 0.02 * (1.0 - strength))
    goals_ceiling = min(max_goals, caps, int(round(caps * min(0.70, goal_rate + 0.18))))
    goals = 0 if goals_ceiling <= 0 else _weighted_randint(rng, 0, goals_ceiling, bias=(0.15 + 0.35 * ability))

    return (min(caps, max_caps), min(goals, caps, max_goals))


def _maybe_pick_random_opponent_nation(
    rng: random.Random,
    nation_lookup: Dict[str, Tuple[int, int]],
    exclude_names: Sequence[str] = (),
    own_nation_name: Optional[str] = None,
) -> Optional[Tuple[int, int]]:
    if not nation_lookup:
        return None
    excludes = {str(x).strip().lower() for x in (exclude_names or ()) if str(x).strip()}
    keys = [k for k in nation_lookup.keys() if k not in excludes]
    if not keys:
        return None

    mode = str(_INTL_OPPONENT_MODE).strip().lower()
    if mode != 'similar' or not own_nation_name:
        return nation_lookup[rng.choice(keys)]

    own_sf = float(_intl_strength_factor(own_nation_name))
    sim = float(_INTL_OPPONENT_SIMILARITY)
    if sim < 0.0: sim = 0.0
    if sim > 1.0: sim = 1.0

    weights = []
    for k in keys:
        sf = float(_intl_strength_factor(k))
        w = max(1e-6, 1.0 - abs(sf - own_sf))
        w = w ** (1.0 + 3.0 * sim)
        weights.append(w)

    try:
        pick = rng.choices(keys, weights=weights, k=1)[0]
    except Exception:
        pick = rng.choice(keys)
    return nation_lookup[pick]


def _random_date_between(rng: random.Random, start: dt.date, end: dt.date) -> dt.date:
    if end < start:
        start, end = end, start
    days = (end - start).days
    if days <= 0:
        return start
    return start + dt.timedelta(days=rng.randint(0, days))


def _pick_primary_nationality_info_default(rng: random.Random) -> int:
    """Default primary nationality info bias when user has not explicitly overridden it.

    Target behaviour:
      - ~95% Born In Nation (85)
      - ~5% spread across other plausible values
    """
    r = rng.random()
    if r < 0.95:
        return 85  # Born In Nation
    # small tail for variety; weighted towards common/credible outcomes
    r2 = rng.random()
    if r2 < 0.45:
        return 84  # Relative Born In Nation
    if r2 < 0.75:
        return 80  # Eligible For Nation
    if r2 < 0.90:
        return 83  # Declared For Nation
    return 0       # No info

__all__ = [k for k in globals().keys() if not k.startswith('__')]
