# -*- coding: utf-8 -*-
from __future__ import annotations

# Names + weighting helpers (extracted)
# This file is auto-generated by fm26_patch_peoplegen_extract_names_v1.py

import csv
import os
import random
from typing import Dict, List, Tuple, Optional

# Defaults (generator may override via configure_from_globals)
_APPEARANCE_MODE = "profile"
_GLOBAL_ETH_RANGE: Tuple[int, int] = (0, 10)
_GLOBAL_SKIN_RANGE: Tuple[int, int] = (0, 19)
_GLOBAL_HAIR_RANGE: Tuple[int, int] = (0, 6)
_HAIR_LEN_WEIGHTS_FEMALE = (1.0, 1.0, 1.0, 1.0)
_HAIR_LEN_WEIGHTS_MALE = (1.0, 1.0, 1.0, 1.0)

def configure_from_globals(g: dict) -> None:
    """Best-effort sync of config globals from fm26_people_generator.py."""
    for k in (
        "_APPEARANCE_MODE",
        "_GLOBAL_ETH_RANGE",
        "_GLOBAL_SKIN_RANGE",
        "_GLOBAL_HAIR_RANGE",
        "_HAIR_LEN_WEIGHTS_FEMALE",
        "_HAIR_LEN_WEIGHTS_MALE",
        "_BODY_TYPE_W123",
        "_BODY_TYPE_W4",
        "_BODY_TYPE_W5",
    ):
        if k in g:
            globals()[k] = g[k]

# -------------------------------------------------------------------

def _load_name_rows(path: str) -> List[Dict[str, object]]:
    """
    Loads CSV rows for names.
    Supported columns (case-insensitive):
      # Name
      # Nationality / Nation
      # Weight      (optional; defaults to 1)
      # Frequency   (optional; defaults to 1)
    Backwards compatible with old 1- or 2-column CSVs.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(path)
    rows: List[Dict[str, object]] = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        sample = f.read(4096)
        f.seek(0)
        s = sample.lower()
        has_header = ("name" in s and ("nationality" in s or ",nation" in s or ",weight" in s or ",frequency" in s))
        if has_header:
            dr = csv.DictReader(f)
            for d in dr:
                if not d:
                    continue
                name = (d.get("Name") or d.get("name") or "").strip()
                nat = (d.get("Nationality") or d.get("nationality") or d.get("Nation") or d.get("nation") or "").strip()
                weight = _to_pos_float(d.get("Weight") or d.get("weight") or 1, 1.0)
                freq = _to_pos_float(
                    d.get("Frequency") or d.get("frequency") or d.get("Freq") or d.get("freq") or 1,
                    1.0
                )
                if name:
                    rows.append({"name": name, "nationality": nat, "weight": weight, "frequency": freq})
        else:
            for row in csv.reader(f):
                if not row:
                    continue
                name = (row[0] or "").strip()
                if not name or name.lower() == "name":
                    continue
                nat = (row[1] or "").strip() if len(row) > 1 else ""
                if nat.lower() in ("nationality", "nation"):
                    nat = ""
                weight = _to_pos_float(row[2], 1.0) if len(row) > 2 else 1.0
                freq = _to_pos_float(row[3], 1.0) if len(row) > 3 else 1.0
                rows.append({"name": name, "nationality": nat, "weight": weight, "frequency": freq})
    if not rows:
        raise ValueError(f"No names loaded from {path}")
    return rows

def _load_names(path: str) -> List[str]:
    return [str(r["name"]) for r in _load_name_rows(path)]

def _norm_nat(s: str) -> str:
    s = (s or "").strip().lower()
    s = s.replace("brzail", "brazil").replace("argentia", "argentina")
    return s

def _weighted_name_choice(name_rng: random.Random, rows: List[Dict[str, object]]) -> str:
    if not rows:
        return ""
    names: List[str] = []
    weights: List[float] = []
    for r in rows:
        nm = str(r.get("name", "") or "").strip()
        if not nm:
            continue
        w = _to_pos_float(r.get("weight", 1), 1.0)
        f = _to_pos_float(r.get("frequency", 1), 1.0)
        eff = max(1e-9, w * f)
        names.append(nm)
        weights.append(eff)
    if not names:
        return ""
    try:
        return name_rng.choices(names, weights=weights, k=1)[0]
    except Exception:
        # Safe fallback if weights ever fail
        return name_rng.choice(names)

def _pick_name_weighted(name_rng: random.Random, rows: List[Dict[str, object]], primary_nation_name: str, local_bias: float = 0.85) -> str:
    if not rows:
        return ""
    pn = _norm_nat(primary_nation_name)
    local = [r for r in rows if _norm_nat(str(r.get("nationality", ""))) == pn]
    foreign = [r for r in rows if _norm_nat(str(r.get("nationality", ""))) != pn]
    if local and foreign:
        pool = local if name_rng.random() < local_bias else foreign
        return _weighted_name_choice(name_rng, pool)
    if local:
        return _weighted_name_choice(name_rng, local)
    return _weighted_name_choice(name_rng, rows)

def _ethnicity_profile_for_nation(nation_name: str) -> Dict[str, Tuple[int, int]]:
    n = _norm_nat(nation_name)
    if n in ("scotland", "england", "france"):
        return {"ethnicity": (0, 2), "skin": (0, 5), "hair_colour": (0, 4)}
    if n in ("argentina",):
        return {"ethnicity": (0, 5), "skin": (2, 10), "hair_colour": (0, 5)}
    if n in ("brazil",):
        return {"ethnicity": (0, 10), "skin": (2, 18), "hair_colour": (0, 6)}
    return {"ethnicity": (0, 10), "skin": (0, 19), "hair_colour": (0, 6)}

def _rand_from_rng_range(rng: random.Random, lo: int, hi: int) -> int:
    lo2 = int(min(lo, hi)); hi2 = int(max(lo, hi))
    return rng.randint(lo2, hi2)

def _default_appearance_values(rng: random.Random, nation_name: str, gender_val: int) -> Dict[str, int]:
    if str(_APPEARANCE_MODE).strip().lower() == 'global':
        prof = {'ethnicity': _GLOBAL_ETH_RANGE, 'skin': _GLOBAL_SKIN_RANGE, 'hair_colour': _GLOBAL_HAIR_RANGE}
    else:
        prof = _ethnicity_profile_for_nation(nation_name)
    if gender_val == 1:
        hair_length = rng.choices([0, 1, 2, 3], weights=list(_HAIR_LEN_WEIGHTS_FEMALE), k=1)[0]
    else:
        hair_length = rng.choices([0, 1, 2, 3], weights=list(_HAIR_LEN_WEIGHTS_MALE), k=1)[0]
    return {
        "ethnicity_value": _rand_from_rng_range(rng, *prof["ethnicity"]),
        "skin_tone_value": _rand_from_rng_range(rng, *prof["skin"]),
        "hair_colour_value": _rand_from_rng_range(rng, *prof["hair_colour"]),
        "hair_length_value": int(hair_length),
    }



# Export everything (including underscore helpers) for generator compatibility
__all__ = [k for k in globals().keys() if not k.startswith("__")]
