# -*- coding: utf-8 -*-
from __future__ import annotations

# Nationality info mapping (extracted)
# Auto-generated by fm26_patch_peoplegen_cleanup_after_modularisation_v1.py

import re
from typing import Dict, List, Optional

NATIONALITY_INFO_ORDER_VALUES = [0, 85, 84, 83, 80, 86, 81, 87, 88, 82, 89, 90]

NATIONALITY_INFO_VALUE_TO_NAME: Dict[int, str] = {
    0: "No info",
    85: "Born In Nation",
    84: "Relative Born In Nation",
    83: "Declared For Nation",
    80: "Eligible For Nation",
    86: "Not Eligible For Nation",
    81: "Has Played For Nation",
    87: "Gained Citizenship Through Relative",
    88: "Gained Citizenship But Not Eligible For Nation Yet",
    82: "Gained Citizenship But Treated As Foreign",
    89: "Gained Citizenship And Declared For Nation",
    90: "Gained Citizenship Through Relative But Not Eligible For Nation Yet",
}

def _norm_key(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", (s or "").strip().lower())

NATIONALITY_INFO_NAME_TO_VALUE: Dict[str, int] = {}
for _v, _name in NATIONALITY_INFO_VALUE_TO_NAME.items():
    NATIONALITY_INFO_NAME_TO_VALUE[_norm_key(_name)] = _v
# Helpful aliases
NATIONALITY_INFO_NAME_TO_VALUE.update({
    _norm_key("none"): 0,
    _norm_key("noinfo"): 0,
    _norm_key("born"): 85,
    _norm_key("relativeborn"): 84,
    _norm_key("declared"): 83,
    _norm_key("eligible"): 80,
    _norm_key("noteligible"): 86,
    _norm_key("played"): 81,
    _norm_key("gainedcitizenshipthroughrelative"): 87,
    _norm_key("gainedcitizenshipnoteligible"): 88,
    _norm_key("treatedasforeign"): 82,
    _norm_key("gainedcitizenshipdeclared"): 89,
    _norm_key("relativecitizenshipnoteligible"): 90,
    _norm_key("born in nation"): 85,
    _norm_key("borninnation"): 85,
    _norm_key("relative born in nation"): 84,
    _norm_key("declared for nation"): 83,
    _norm_key("not eligible"): 86,
    _norm_key("treated as foreign"): 82,
    _norm_key("gained citizenship through relative"): 87,
    _norm_key("gained citizenship not eligible"): 88,
    _norm_key("gained citizenship declared"): 89,
    _norm_key("relative citizenship not eligible"): 90,
})

NATIONALITY_INFO_NAME_TO_VALUE: Dict[str, int] = {}
for _v, _name in NATIONALITY_INFO_VALUE_TO_NAME.items():
    NATIONALITY_INFO_NAME_TO_VALUE[_norm_key(_name)] = _v
# Helpful aliases
NATIONALITY_INFO_NAME_TO_VALUE.update({
    _norm_key("none"): 0,
    _norm_key("noinfo"): 0,
    _norm_key("born"): 85,
    _norm_key("relativeborn"): 84,
    _norm_key("declared"): 83,
    _norm_key("eligible"): 80,
    _norm_key("noteligible"): 86,
    _norm_key("played"): 81,
    _norm_key("gainedcitizenshipthroughrelative"): 87,
    _norm_key("gainedcitizenshipnoteligible"): 88,
    _norm_key("treatedasforeign"): 82,
    _norm_key("gainedcitizenshipdeclared"): 89,
    _norm_key("relativecitizenshipnoteligible"): 90,
    _norm_key("born in nation"): 85,
    _norm_key("borninnation"): 85,
    _norm_key("relative born in nation"): 84,
    _norm_key("declared for nation"): 83,
    _norm_key("not eligible"): 86,
    _norm_key("treated as foreign"): 82,
    _norm_key("gained citizenship through relative"): 87,
    _norm_key("gained citizenship not eligible"): 88,
    _norm_key("gained citizenship declared"): 89,
    _norm_key("relative citizenship not eligible"): 90,
})

def resolve_nationality_info(value: Optional[int] = None, name: Optional[str] = None) -> int:
    if name is not None and str(name).strip() != "":
        raw = str(name).strip()
        if re.fullmatch(r"-?\d+", raw):
            return int(raw)
        k = _norm_key(raw)
        if k in NATIONALITY_INFO_NAME_TO_VALUE:
            return int(NATIONALITY_INFO_NAME_TO_VALUE[k])
        allowed = ", ".join([f"{v}={NATIONALITY_INFO_VALUE_TO_NAME[v]}" for v in NATIONALITY_INFO_ORDER_VALUES])
        raise ValueError(f"Unknown nationality info name: {raw!r}. Allowed: {allowed}")
    if value is None:
        return 85
    return int(value)

def nationality_info_mapping_lines() -> List[str]:
    return [f"{v} = {NATIONALITY_INFO_VALUE_TO_NAME[v]}" for v in NATIONALITY_INFO_ORDER_VALUES]

__all__ = [k for k in globals().keys() if not k.startswith('__')]
