# -*- coding: utf-8 -*-
from __future__ import annotations

# Omit-field helpers (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_omit_v1.py

from typing import Iterable, Set

def _norm_omit_fields(values: Optional[Sequence[str]]) -> set[str]:
    out: set[str] = set()
    if not values:
        return out
    for v in values:
        if v is None:
            continue
        s = str(v).strip().lower().replace(" ", "_").replace("-", "_")
        if s:
            out.add(s)
    return out

__all__ = [k for k in globals().keys() if not k.startswith('__')]
