# -*- coding: utf-8 -*-
from __future__ import annotations

# Path resolution helpers (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_paths_v1.py

import os
from typing import List, Optional

def _fmdata_candidate_paths(path_value: Optional[str]) -> List[str]:
    p = (path_value or "").strip() if path_value is not None else ""
    if not p:
        return []
    cands: List[str] = []
    def _add(v: str) -> None:
        if v and v not in cands:
            cands.append(v)
    _add(p)
    if not os.path.isabs(p):
        _add(os.path.abspath(p))
    try:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        if not os.path.isabs(p):
            _add(os.path.join(script_dir, p))
            _add(os.path.join(script_dir, "fmdata", p))
        else:
            bn = os.path.basename(p)
            _add(os.path.join(script_dir, bn))
            _add(os.path.join(script_dir, "fmdata", bn))
    except Exception:
        pass
    return cands

def _resolve_existing_data_path(path_value: str, *, kind: str = "file") -> str:
    for cand in _fmdata_candidate_paths(path_value):
        if os.path.exists(cand):
            return cand
    return path_value

def _resolve_output_xml_path(path_value: str) -> str:
    p = (path_value or "").strip()
    if not p:
        return p
    if os.path.isabs(p):
        outp = p
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        fmdata_dir = os.path.join(script_dir, "fmdata")
        try:
            os.makedirs(fmdata_dir, exist_ok=True)
        except Exception:
            pass
        outp = os.path.join(fmdata_dir, p)
    try:
        parent = os.path.dirname(outp)
        if parent:
            os.makedirs(parent, exist_ok=True)
    except Exception:
        pass
    return outp

__all__ = [k for k in globals().keys() if not k.startswith('__')]
