# -*- coding: utf-8 -*-
from __future__ import annotations

# Randomness helpers (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_randomness_v1.py

import datetime as dt
import random
import re
from typing import Tuple

# Defaults (generator may override via configure_from_globals)
_BODY_TYPE_W123 = 95.0
_BODY_TYPE_W4 = 4.0
_BODY_TYPE_W5 = 1.0

def configure_from_globals(g: dict) -> None:
    """Best-effort sync of randomness-related globals from generator/CLI."""
    for k in ("_BODY_TYPE_W123", "_BODY_TYPE_W4", "_BODY_TYPE_W5"):
        if k in g:
            globals()[k] = g[k]

# -------------------------------------------------------------------

def _random_body_type_weighted(rng: random.Random) -> int:
    # settings-controlled body type weights: W123, W4, W5
    w123 = float(_BODY_TYPE_W123)
    w4 = float(_BODY_TYPE_W4)
    w5 = float(_BODY_TYPE_W5)
    if w123 < 0: w123 = 0.0
    if w4 < 0: w4 = 0.0
    if w5 < 0: w5 = 0.0
    tot = max(1e-9, w123 + w4 + w5)
    r = rng.random() * tot
    if r < w123:
        return rng.choice((1, 2, 3))
    if r < (w123 + w4):
        return 4
    return 5
def _days_in_month(y: int, m: int) -> int:
    if m == 12:
        return (dt.date(y + 1, 1, 1) - dt.date(y, m, 1)).days
    return (dt.date(y, m + 1, 1) - dt.date(y, m, 1)).days


def _random_dob(rng: random.Random, age: int, base_year: int) -> dt.date:
    y = base_year - age
    m = rng.randint(1, 12)
    d = rng.randint(1, _days_in_month(y, m))
    return dt.date(y, m, d)


def _parse_ymd(s: str) -> dt.date:
    m = re.fullmatch(r"(\d{4})-(\d{2})-(\d{2})", (s or "").strip())
    if not m:
        raise ValueError("DOB must be YYYY-MM-DD")
    y, mo, d = map(int, m.groups())
    return dt.date(y, mo, d)


def _random_dob_between(rng: random.Random, start: dt.date, end: dt.date) -> dt.date:
    """Random date between start and end (inclusive)."""
    if end < start:
        raise ValueError("DOB range end must be >= start")
    a = start.toordinal()
    b = end.toordinal()
    return dt.date.fromordinal(rng.randint(a, b))


def _tv_from_pa(pa: int) -> int:
    """Derive transfer value from PA.

    Range: 100,000 .. 150,000,000 (cap as requested).
    """
    x = max(0, min(200, int(pa)))
    lo = 100_000
    hi = 150_000_000
    return int(lo + ((x / 200.0) ** 3) * (hi - lo))




__all__ = [k for k in globals().keys() if not k.startswith('__')]
