# -*- coding: utf-8 -*-
from __future__ import annotations

# Second nations system (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_second_nations_v1.py

from typing import Dict, List, Tuple, Optional

def configure_from_globals(g: dict) -> None:
    """Copy second-nation knobs/constants from generator globals into this module."""
    for k in (
        'PROP_DECLARED_FOR_YOUTH_NATION',
        'PROP_SECOND_NATIONS',
        '_EXTRA_NATION_P2',
        '_EXTRA_NATION_P3_GIVEN_P2',
        '_EXTRA_NATION_P4_GIVEN_P3',
        '_EXTRA_NATION_P5PLUS_GIVEN_P4',
        '_EXTRA_NATION_CHAIN_P',
        '_EXTRA_NATION_MAX',
    ):
        if k in g:
            globals()[k] = g[k]

# -------------------------------------------------------------------

PROP_DECLARED_FOR_YOUTH_NATION = 1349411961

PROP_SECOND_NATIONS = 1347310195

_EXTRA_NATION_P2 = 0.05

_EXTRA_NATION_P3_GIVEN_P2 = 0.30

_EXTRA_NATION_P4_GIVEN_P3 = (1.0 / 3.0)

_EXTRA_NATION_P5PLUS_GIVEN_P4 = 0.10

_EXTRA_NATION_CHAIN_P = 0.20

_EXTRA_NATION_MAX = 8

def _pick_random_extra_nation_count(rng: random.Random) -> int:
    # settings-controlled extra nationality count
    extras = 0
    if rng.random() < float(_EXTRA_NATION_P2):
        extras = 1
        if rng.random() < float(_EXTRA_NATION_P3_GIVEN_P2):
            extras = 2
            if rng.random() < float(_EXTRA_NATION_P4_GIVEN_P3):
                extras = 3
                if rng.random() < float(_EXTRA_NATION_P5PLUS_GIVEN_P4):
                    extras = 4
                    while extras < int(_EXTRA_NATION_MAX) and rng.random() < float(_EXTRA_NATION_CHAIN_P):
                        extras += 1
    if extras < 0:
        extras = 0
    if extras > int(_EXTRA_NATION_MAX):
        extras = int(_EXTRA_NATION_MAX)
    return extras

def _pick_random_second_nation_nationality_info(rng: random.Random) -> int:
    """Weighted nationality info for randomly generated second/third/etc nations."""
    r = rng.random()
    if r < 0.70:
        return 80  # Eligible For Nation
    if r < 0.88:
        return 84  # Relative Born In Nation
    if r < 0.94:
        return 83  # Declared For Nation
    if r < 0.98:
        return 85  # Born In Nation
    return 0       # No info

def _build_random_extra_second_nations(
    rng: random.Random,
    nations: List[Tuple[int, int, str]],
    primary_nation: Tuple[int, int],
    existing_rows: Optional[List[Dict[str, object]]] = None,
) -> List[Dict[str, object]]:
    """Generate random extra nation rows using FM second-nation row model inputs.

    Returns parsed row dicts compatible with the existing second nation writer:
      {"name", "dbid", "large", "ntin"}

    Important: excludes the player's primary nation and any already-specified nations.
    """
    existing_rows = list(existing_rows or [])
    # Only auto-generate when user has not manually provided second nations.
    if existing_rows:
        return []

    extras_needed = _pick_random_extra_nation_count(rng)
    if extras_needed <= 0:
        return []

    p_dbid, p_large = (int(primary_nation[0]), int(primary_nation[1]))
    excluded = {(p_dbid, p_large)}
    for row in existing_rows:
        try:
            excluded.add((int(row.get("dbid", -1)), int(row.get("large", -1))))
        except Exception:
            pass

    pool = []
    for n in (nations or []):
        if len(n) < 2:
            continue
        dbid = int(n[0])
        large = int(n[1])
        if (dbid, large) in excluded:
            continue
        name = (n[2] if len(n) > 2 else "") or ""
        pool.append((dbid, large, str(name)))

    if not pool:
        return []

    rng.shuffle(pool)
    picked = pool[:min(extras_needed, len(pool))]
    out: List[Dict[str, object]] = []
    for dbid, large, name in picked:
        out.append({
            "name": name,
            "dbid": int(dbid),
            "large": int(large),
            "ntin": int(_pick_random_second_nation_nationality_info(rng)),
        })
    return out

PROP_DATE_JOINED_CLUB = 1348692580
PROP_DATE_LAST_SIGNED = 1348694884
PROP_CONTRACT_EXPIRES = 1348691320
PROP_SQUAD_STATUS = 1347253105
PROP_CA = 1346584898
PROP_PA = 1347436866
PROP_CURRENT_REP = 1346589264
PROP_HOME_REP = 1346916944
PROP_WORLD_REP = 1347899984
PROP_LEFT_FOOT = 1346661478
PROP_RIGHT_FOOT = 1346663017
PROP_TRANSFER_VALUE = 1348630085


# --- Position distribution defaults (editable via CLI for RANDOM positions) ---

DEFAULT_VERSION = 3727
DEFAULT_RULE_GROUP_VERSION = 1630
DEFAULT_EDVB = 1
DEFAULT_ORVS = "2600"
DEFAULT_SVVS = "2600"
DEFAULT_NNAT_ODVL = 3285649982205  # safe default seen in samples

INT32_MOD = 2147483646
INT64_MOD = 9223372036854775806

from peoplegen import ids as _ids

from peoplegen import xml_writer as _xmlw
# (XML writer extracted to peoplegen/xml_writer.py)
_int = _xmlw._int
_large = _xmlw._large
_uns = _xmlw._uns
_str = _xmlw._str
_bool = _xmlw._bool
_null = _xmlw._null
_date = _xmlw._date
_rec = _xmlw._rec
_attr = _xmlw._attr
_create = _xmlw._create
_count_existing = _xmlw._count_existing
_append = _xmlw._append



# --- Legacy ID helpers (compat) ---
# Some older code paths still call _id32/_id64/_uniq/_reserve_id_namespace.
# Keep aliases so modularisation doesn't break runtime.
_id32 = _ids.id32
_id64 = _ids.id64
_uniq = _ids.uniq
_reserve_id_namespace = _ids.reserve_id_namespace
# ---------------------------------

# (IDs/registry extracted to peoplegen/ids.py)

# ---- csv helpers ----
from peoplegen import library as _lib
from peoplegen import paths as _paths
from peoplegen import omit as _omit
# (omit helpers extracted to peoplegen/omit.py)
_norm_omit_fields = _omit._norm_omit_fields


# (path helpers extracted to peoplegen/paths.py)
_fmdata_candidate_paths = _paths._fmdata_candidate_paths
_resolve_existing_data_path = _paths._resolve_existing_data_path
_resolve_output_xml_path = _paths._resolve_output_xml_path


from peoplegen import international as _intl
# (international stats extracted to peoplegen/international.py)
try:
    _intl.configure_from_globals(globals())
except Exception:
    pass
PROP_INTERNATIONAL_RETIREMENT = _intl.PROP_INTERNATIONAL_RETIREMENT
PROP_INTERNATIONAL_RETIREMENT_DATE = _intl.PROP_INTERNATIONAL_RETIREMENT_DATE
PROP_INTERNATIONAL_APPS = _intl.PROP_INTERNATIONAL_APPS
PROP_INTERNATIONAL_GOALS = _intl.PROP_INTERNATIONAL_GOALS
PROP_U21_INTERNATIONAL_APPS = _intl.PROP_U21_INTERNATIONAL_APPS
PROP_U21_INTERNATIONAL_GOALS = _intl.PROP_U21_INTERNATIONAL_GOALS
PROP_INTERNATIONAL_DEBUT_DATE = _intl.PROP_INTERNATIONAL_DEBUT_DATE
PROP_INTERNATIONAL_DEBUT_AGAINST = _intl.PROP_INTERNATIONAL_DEBUT_AGAINST
PROP_U21_INTERNATIONAL_DEBUT_DATE = _intl.PROP_U21_INTERNATIONAL_DEBUT_DATE
PROP_U21_INTERNATIONAL_DEBUT_AGAINST = _intl.PROP_U21_INTERNATIONAL_DEBUT_AGAINST
_INTL_PLAY_PROB_MULT = _intl._INTL_PLAY_PROB_MULT
_INTL_OPPONENT_MODE = _intl._INTL_OPPONENT_MODE
_INTL_OPPONENT_SIMILARITY = _intl._INTL_OPPONENT_SIMILARITY
_intl_strength_factor = _intl._intl_strength_factor
_estimate_international_stats = _intl._estimate_international_stats



from peoplegen import positions as _pos
# (positions extracted to peoplegen/positions.py)
POS_PROPS = _pos.POS_PROPS
_to_pos_float = _pos._to_pos_float
_pick_weighted = _pos._pick_weighted
_random_primary_position = _pos._random_primary_position
_sample_outfield_n20 = _pos._sample_outfield_n20
_extra_pos_weight = _pos._extra_pos_weight
_dev_pos_weight = _pos._dev_pos_weight
_apply_dev_value = _pos._apply_dev_value
_pos_map_auto_random = _pos._pos_map_auto_random
_pos_map_advanced = _pos._pos_map_advanced


# (nation lookup helpers extracted to peoplegen/library.py)
_norm_name_key = _lib._norm_name_key
_build_nation_lookup = _lib._build_nation_lookup
_resolve_nation_from_lookup = _lib._resolve_nation_from_lookup
_parse_second_nation_specs = _lib._parse_second_nation_specs

# (master library CSV parsing extracted to peoplegen/library.py)
load_master_library = _lib.load_master_library


# ---- names ----
from peoplegen import names as _names
# (names + weighting extracted to peoplegen/names.py)
try:
    _names.configure_from_globals(globals())
except Exception:
    pass
# Re-export everything (including underscore helpers)
globals().update({k: v for k, v in vars(_names).items() if not k.startswith("__")})


# ---- randomness ----
from peoplegen import randomness as _rand
# (randomness extracted to peoplegen/randomness.py)
try:
    _rand.configure_from_globals(globals())
except Exception:
    pass
globals().update({k: v for k, v in vars(_rand).items() if not k.startswith('__')})


# ---- xml helpers ----

def _attr_second_nations_listop(person_uid: int, rid: int, ver: int, *, lsop: int, dbid: Optional[int] = None,
                                large: Optional[int] = None, ntin: Optional[int] = None,
                                element_id: int = 1851880553) -> str:
    # FM26 exported shape: the nation row and per-row nationality-info row are separate records.
    # This function writes only the nation row (id=1851880553). ntin is ignored here by design.
    if int(lsop) == 0:
        newv = '<record id="new_value">\n' + f'\t\t\t\t{_int("lsop", 0)}\n' + "\t\t\t</record>"
        return _attr(person_uid, PROP_SECOND_NATIONS, newv, rid, ver)

    if dbid is None or large is None:
        raise ValueError("second nation lsop=1 requires dbid and large")

    newv = (
        '<record id="new_value">\n'
        + f'\t\t\t\t{_uns("id", int(element_id))}\n'
        + '\t\t\t\t<record id="value">\n'
        + f'\t\t\t\t\t{_large("Nnat", int(large))}\n'
        + f'\t\t\t\t\t{_int("DBID", int(dbid))}\n'
        + '\t\t\t\t</record>\n'
        + f'\t\t\t\t{_int("lsop", 1)}\n'
        + '\t\t\t\t<record id="olvl">\n'
        + f'\t\t\t\t\t{_int("ntin", 80)}\n'
        + f'\t\t\t\t\t{_null("nation")}\n'
        + '\t\t\t\t</record>\n'
        + '\t\t\t</record>'
    )
    return _attr(person_uid, PROP_SECOND_NATIONS, newv, rid, ver)

def _attr_second_nation_nationality_info(person_uid: int, rid: int, ver: int, *, nation_large: int, ntin_value: int) -> str:
    # FM26 exported per-row nationality info (linked to a second nation by Nnat)
    newv = (
        '<record id="new_value">\n'
        + f'\t\t\t\t{_uns("id", 1853122926)}\n'
        + f'\t\t\t\t{_int("value", int(ntin_value))}\n'
        + f'\t\t\t\t{_int("lsop", 1)}\n'
        + '\t\t\t\t<record id="olvl">\n'
        + f'\t\t\t\t\t{_int("ntin", 80)}\n'
        + '\t\t\t\t\t<record id="nation">\n'
        + f'\t\t\t\t\t\t{_large("Nnat", int(nation_large))}\n'
        + '\t\t\t\t\t</record>\n'
        + '\t\t\t\t</record>\n'
        + '\t\t\t</record>'
    )
    return _attr(person_uid, PROP_SECOND_NATIONS, newv, rid, ver)



__all__ = [k for k in globals().keys() if not k.startswith('__')]
