# -*- coding: utf-8 -*-
from __future__ import annotations

# Validation / normalization helpers (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_validation_v1.py

import datetime as dt
from typing import Any, Callable, Iterable, Optional, Set, Tuple

from peoplegen.omit import _norm_omit_fields

IsOmittedFn = Callable[..., bool]

def validate_and_prepare(*,
    wage_min: Any,
    wage_max: Any,
    wage: Any,
    rep_min: Any,
    rep_max: Any,
    rep_current: Any,
    rep_home: Any,
    rep_world: Any,
    transfer_mode: Any,
    transfer_value: Any,
    transfer_min: Any,
    transfer_max: Any,
    fixed_height: Any,
    height_min: Any,
    height_max: Any,
    dob_start: Any,
    dob_end: Any,
    moved_to_nation_date: Any,
    joined_club_date: Any,
    international_retirement_date: Any,
    international_debut_date: Any,
    u21_international_debut_date: Any,
    international_apps: Any,
    international_goals: Any,
    u21_international_apps: Any,
    u21_international_goals: Any,
    omit_fields: Any,
) -> Tuple[int, int, int, int, int, int, int, int, int, str, int, int, int, int, Set[str], IsOmittedFn]:
    """Validate/normalize inputs and build the omit checker.

    Returns:
      wage_min, wage_max, wage,
      rep_min, rep_max, rep_current, rep_home, rep_world,
      transfer_mode, transfer_value, transfer_min, transfer_max,
      TV_LO, TV_HI,
      _omit_fields, _is_omitted
    """
    # Wage (minimum 30)
    wage_min = max(30, int(wage_min))
    wage_max = max(wage_min, int(wage_max))
    wage = int(wage)

    # Reputation (0..200)
    rep_min = int(rep_min)
    rep_max = int(rep_max)
    rep_current = int(rep_current)
    rep_home = int(rep_home)
    rep_world = int(rep_world)

    # Transfer value
    transfer_mode = (transfer_mode or "auto").lower().strip()
    if transfer_mode not in ("auto", "fixed", "range"):
        raise ValueError("transfer_mode must be auto|fixed|range")
    transfer_value = int(transfer_value)
    transfer_min = int(transfer_min)
    transfer_max = int(transfer_max)
    TV_LO = 100_000
    TV_HI = 2_000_000_000  # allow fixed values above 150m

    if fixed_height is not None:
        if not (150 <= fixed_height <= 210):
            raise ValueError("height must be 150..210")
    else:
        if not (150 <= height_min <= 210 and 150 <= height_max <= 210 and height_min <= height_max):
            raise ValueError("height range must be within 150..210 and min<=max")

    if (dob_start is None) ^ (dob_end is None):
        raise ValueError("DOB range requires both dob_start and dob_end")
    if dob_start is not None and dob_end is not None and dob_end < dob_start:
        raise ValueError("DOB range end must be >= start")
    if moved_to_nation_date is not None and not isinstance(moved_to_nation_date, dt.date):
        raise ValueError("moved_to_nation_date must be a valid date")
    if joined_club_date is not None and not isinstance(joined_club_date, dt.date):
        raise ValueError("joined_club_date must be a valid date")
    if international_retirement_date is not None and not isinstance(international_retirement_date, dt.date):
        raise ValueError("international_retirement_date must be a valid date")
    if international_debut_date is not None and not isinstance(international_debut_date, dt.date):
        raise ValueError("international_debut_date must be a valid date")
    if u21_international_debut_date is not None and not isinstance(u21_international_debut_date, dt.date):
        raise ValueError("u21_international_debut_date must be a valid date")
    for _n, _v in (("international_apps", international_apps), ("international_goals", international_goals), ("u21_international_apps", u21_international_apps), ("u21_international_goals", u21_international_goals)):
        if _v is not None:
            _iv = int(_v)
            if _iv < 0 and _iv not in (-1, -2):
                raise ValueError(f"{_n} must be >= 0 (or -1 omit / -2 auto)")

    _omit_fields = _norm_omit_fields(omit_fields)
    def _is_omitted(*names: str) -> bool:
        # Support group aliases from GUI (e.g. --omit-field reputation)
        rep_group = {"rep_current", "rep_home", "rep_world"}
        for _name in names:
            n = str(_name).strip().lower().replace(" ", "_").replace("-", "_")
            if n in _omit_fields:
                return True
            if n in rep_group and "reputation" in _omit_fields:
                return True
        return False


    return (
        wage_min, wage_max, wage,
        rep_min, rep_max, rep_current, rep_home, rep_world,
        transfer_mode, transfer_value, transfer_min, transfer_max,
        TV_LO, TV_HI,
        _omit_fields, _is_omitted,
    )

__all__ = [k for k in globals().keys() if not k.startswith('__')]
