# -*- coding: utf-8 -*-
from __future__ import annotations

# XML helper utilities (extracted)
# Auto-generated by fm26_patch_peoplegen_extract_xml_helpers_and_dedupe_second_nations_v1.py

import random
from typing import Tuple

def _foot(rng: random.Random, feet_mode: str) -> Tuple[int, int]:
    """Return (left_foot, right_foot) 1..20.

    Supported modes:
      # left_only  -> left=20, right=1..5
      # left       -> left=20, right=6..14
      # right_only -> right=20, left=1..5
      # right      -> right=20, left=6..14
      # both       -> left=20, right=20
      # random     -> weighted mix of the above (keeps a realistic spread)

    Notes:
      # Any unknown mode falls back to 'random'
      # Exactly one foot is forced to 20 for left/right variants
    """
    mode = (feet_mode or "random").strip().lower()

    if mode == "random":
        # Weighted spread (sums to 100):
        # left_only 10%, left 30%, right_only 10%, right 30%, both 20%
        r = rng.random()
        if r < 0.10:
            mode = "left_only"
        elif r < 0.40:
            mode = "left"
        elif r < 0.50:
            mode = "right_only"
        elif r < 0.80:
            mode = "right"
        else:
            mode = "both"

    if mode == "both":
        return 20, 20

    if mode == "left_only":
        return 20, rng.randint(1, 5)

    if mode == "right_only":
        return rng.randint(1, 5), 20

    if mode == "right":
        return rng.randint(6, 14), 20

    # default 'left'
    return 20, rng.randint(6, 14)

def _rep_triplet(rng: random.Random, rep_min: int, rep_max: int) -> Tuple[int, int, int]:
    """Return (current, home, world) with current >= home >= world."""
    lo = int(rep_min)
    hi = int(rep_max)
    if hi < lo:
        lo, hi = hi, lo
    lo = max(0, lo)
    hi = min(200, hi)
    current = rng.randint(lo, hi)
    home = rng.randint(lo, current)
    world = rng.randint(lo, home)
    return current, home, world

__all__ = [k for k in globals().keys() if not k.startswith('__')]
